// Code generated by ent, DO NOT EDIT.

package termsassent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldUpdatedAt, v))
}

// TermsVersion applies equality check predicate on the "terms_version" field. It's identical to TermsVersionEQ.
func TermsVersion(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldTermsVersion, v))
}

// AcceptedAt applies equality check predicate on the "accepted_at" field. It's identical to AcceptedAtEQ.
func AcceptedAt(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldAcceptedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLTE(FieldUpdatedAt, v))
}

// TermsVersionEQ applies the EQ predicate on the "terms_version" field.
func TermsVersionEQ(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldTermsVersion, v))
}

// TermsVersionNEQ applies the NEQ predicate on the "terms_version" field.
func TermsVersionNEQ(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNEQ(FieldTermsVersion, v))
}

// TermsVersionIn applies the In predicate on the "terms_version" field.
func TermsVersionIn(vs ...string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldIn(FieldTermsVersion, vs...))
}

// TermsVersionNotIn applies the NotIn predicate on the "terms_version" field.
func TermsVersionNotIn(vs ...string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNotIn(FieldTermsVersion, vs...))
}

// TermsVersionGT applies the GT predicate on the "terms_version" field.
func TermsVersionGT(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGT(FieldTermsVersion, v))
}

// TermsVersionGTE applies the GTE predicate on the "terms_version" field.
func TermsVersionGTE(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGTE(FieldTermsVersion, v))
}

// TermsVersionLT applies the LT predicate on the "terms_version" field.
func TermsVersionLT(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLT(FieldTermsVersion, v))
}

// TermsVersionLTE applies the LTE predicate on the "terms_version" field.
func TermsVersionLTE(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLTE(FieldTermsVersion, v))
}

// TermsVersionContains applies the Contains predicate on the "terms_version" field.
func TermsVersionContains(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldContains(FieldTermsVersion, v))
}

// TermsVersionHasPrefix applies the HasPrefix predicate on the "terms_version" field.
func TermsVersionHasPrefix(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldHasPrefix(FieldTermsVersion, v))
}

// TermsVersionHasSuffix applies the HasSuffix predicate on the "terms_version" field.
func TermsVersionHasSuffix(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldHasSuffix(FieldTermsVersion, v))
}

// TermsVersionEqualFold applies the EqualFold predicate on the "terms_version" field.
func TermsVersionEqualFold(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEqualFold(FieldTermsVersion, v))
}

// TermsVersionContainsFold applies the ContainsFold predicate on the "terms_version" field.
func TermsVersionContainsFold(v string) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldContainsFold(FieldTermsVersion, v))
}

// AcceptedAtEQ applies the EQ predicate on the "accepted_at" field.
func AcceptedAtEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldEQ(FieldAcceptedAt, v))
}

// AcceptedAtNEQ applies the NEQ predicate on the "accepted_at" field.
func AcceptedAtNEQ(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNEQ(FieldAcceptedAt, v))
}

// AcceptedAtIn applies the In predicate on the "accepted_at" field.
func AcceptedAtIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldIn(FieldAcceptedAt, vs...))
}

// AcceptedAtNotIn applies the NotIn predicate on the "accepted_at" field.
func AcceptedAtNotIn(vs ...time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldNotIn(FieldAcceptedAt, vs...))
}

// AcceptedAtGT applies the GT predicate on the "accepted_at" field.
func AcceptedAtGT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGT(FieldAcceptedAt, v))
}

// AcceptedAtGTE applies the GTE predicate on the "accepted_at" field.
func AcceptedAtGTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldGTE(FieldAcceptedAt, v))
}

// AcceptedAtLT applies the LT predicate on the "accepted_at" field.
func AcceptedAtLT(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLT(FieldAcceptedAt, v))
}

// AcceptedAtLTE applies the LTE predicate on the "accepted_at" field.
func AcceptedAtLTE(v time.Time) predicate.TermsAssent {
	return predicate.TermsAssent(sql.FieldLTE(FieldAcceptedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TermsAssent {
	return predicate.TermsAssent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TermsAssent {
	return predicate.TermsAssent(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TermsAssent) predicate.TermsAssent {
	return predicate.TermsAssent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TermsAssent) predicate.TermsAssent {
	return predicate.TermsAssent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TermsAssent) predicate.TermsAssent {
	return predicate.TermsAssent(sql.NotPredicates(p))
}
