// Code generated by ent, DO NOT EDIT.

package billingretention

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldUpdatedAt, v))
}

// Plan applies equality check predicate on the "plan" field. It's identical to PlanEQ.
func Plan(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldPlan, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStatus, v))
}

// StripeCustomerID applies equality check predicate on the "stripe_customer_id" field. It's identical to StripeCustomerIDEQ.
func StripeCustomerID(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStripeCustomerID, v))
}

// StripeSubscriptionID applies equality check predicate on the "stripe_subscription_id" field. It's identical to StripeSubscriptionIDEQ.
func StripeSubscriptionID(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStripeSubscriptionID, v))
}

// TrialExpiresAt applies equality check predicate on the "trial_expires_at" field. It's identical to TrialExpiresAtEQ.
func TrialExpiresAt(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldTrialExpiresAt, v))
}

// RetainedAt applies equality check predicate on the "retained_at" field. It's identical to RetainedAtEQ.
func RetainedAt(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldRetainedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldUpdatedAt, v))
}

// PlanEQ applies the EQ predicate on the "plan" field.
func PlanEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldPlan, v))
}

// PlanNEQ applies the NEQ predicate on the "plan" field.
func PlanNEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldPlan, v))
}

// PlanIn applies the In predicate on the "plan" field.
func PlanIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldPlan, vs...))
}

// PlanNotIn applies the NotIn predicate on the "plan" field.
func PlanNotIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldPlan, vs...))
}

// PlanGT applies the GT predicate on the "plan" field.
func PlanGT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldPlan, v))
}

// PlanGTE applies the GTE predicate on the "plan" field.
func PlanGTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldPlan, v))
}

// PlanLT applies the LT predicate on the "plan" field.
func PlanLT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldPlan, v))
}

// PlanLTE applies the LTE predicate on the "plan" field.
func PlanLTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldPlan, v))
}

// PlanContains applies the Contains predicate on the "plan" field.
func PlanContains(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContains(FieldPlan, v))
}

// PlanHasPrefix applies the HasPrefix predicate on the "plan" field.
func PlanHasPrefix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasPrefix(FieldPlan, v))
}

// PlanHasSuffix applies the HasSuffix predicate on the "plan" field.
func PlanHasSuffix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasSuffix(FieldPlan, v))
}

// PlanEqualFold applies the EqualFold predicate on the "plan" field.
func PlanEqualFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEqualFold(FieldPlan, v))
}

// PlanContainsFold applies the ContainsFold predicate on the "plan" field.
func PlanContainsFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContainsFold(FieldPlan, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContainsFold(FieldStatus, v))
}

// StripeCustomerIDEQ applies the EQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDNEQ applies the NEQ predicate on the "stripe_customer_id" field.
func StripeCustomerIDNEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldStripeCustomerID, v))
}

// StripeCustomerIDIn applies the In predicate on the "stripe_customer_id" field.
func StripeCustomerIDIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDNotIn applies the NotIn predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldStripeCustomerID, vs...))
}

// StripeCustomerIDGT applies the GT predicate on the "stripe_customer_id" field.
func StripeCustomerIDGT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldStripeCustomerID, v))
}

// StripeCustomerIDGTE applies the GTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDGTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDLT applies the LT predicate on the "stripe_customer_id" field.
func StripeCustomerIDLT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldStripeCustomerID, v))
}

// StripeCustomerIDLTE applies the LTE predicate on the "stripe_customer_id" field.
func StripeCustomerIDLTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldStripeCustomerID, v))
}

// StripeCustomerIDContains applies the Contains predicate on the "stripe_customer_id" field.
func StripeCustomerIDContains(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContains(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasPrefix applies the HasPrefix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasPrefix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasPrefix(FieldStripeCustomerID, v))
}

// StripeCustomerIDHasSuffix applies the HasSuffix predicate on the "stripe_customer_id" field.
func StripeCustomerIDHasSuffix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasSuffix(FieldStripeCustomerID, v))
}

// StripeCustomerIDIsNil applies the IsNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDIsNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIsNull(FieldStripeCustomerID))
}

// StripeCustomerIDNotNil applies the NotNil predicate on the "stripe_customer_id" field.
func StripeCustomerIDNotNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotNull(FieldStripeCustomerID))
}

// StripeCustomerIDEqualFold applies the EqualFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDEqualFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEqualFold(FieldStripeCustomerID, v))
}

// StripeCustomerIDContainsFold applies the ContainsFold predicate on the "stripe_customer_id" field.
func StripeCustomerIDContainsFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContainsFold(FieldStripeCustomerID, v))
}

// StripeSubscriptionIDEQ applies the EQ predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDNEQ applies the NEQ predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNEQ(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDIn applies the In predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldStripeSubscriptionID, vs...))
}

// StripeSubscriptionIDNotIn applies the NotIn predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNotIn(vs ...string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldStripeSubscriptionID, vs...))
}

// StripeSubscriptionIDGT applies the GT predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDGT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDGTE applies the GTE predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDGTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDLT applies the LT predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDLT(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDLTE applies the LTE predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDLTE(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDContains applies the Contains predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDContains(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContains(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDHasPrefix applies the HasPrefix predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDHasPrefix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasPrefix(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDHasSuffix applies the HasSuffix predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDHasSuffix(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldHasSuffix(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDIsNil applies the IsNil predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDIsNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIsNull(FieldStripeSubscriptionID))
}

// StripeSubscriptionIDNotNil applies the NotNil predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDNotNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotNull(FieldStripeSubscriptionID))
}

// StripeSubscriptionIDEqualFold applies the EqualFold predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDEqualFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEqualFold(FieldStripeSubscriptionID, v))
}

// StripeSubscriptionIDContainsFold applies the ContainsFold predicate on the "stripe_subscription_id" field.
func StripeSubscriptionIDContainsFold(v string) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldContainsFold(FieldStripeSubscriptionID, v))
}

// TrialExpiresAtEQ applies the EQ predicate on the "trial_expires_at" field.
func TrialExpiresAtEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldTrialExpiresAt, v))
}

// TrialExpiresAtNEQ applies the NEQ predicate on the "trial_expires_at" field.
func TrialExpiresAtNEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldTrialExpiresAt, v))
}

// TrialExpiresAtIn applies the In predicate on the "trial_expires_at" field.
func TrialExpiresAtIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldTrialExpiresAt, vs...))
}

// TrialExpiresAtNotIn applies the NotIn predicate on the "trial_expires_at" field.
func TrialExpiresAtNotIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldTrialExpiresAt, vs...))
}

// TrialExpiresAtGT applies the GT predicate on the "trial_expires_at" field.
func TrialExpiresAtGT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldTrialExpiresAt, v))
}

// TrialExpiresAtGTE applies the GTE predicate on the "trial_expires_at" field.
func TrialExpiresAtGTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldTrialExpiresAt, v))
}

// TrialExpiresAtLT applies the LT predicate on the "trial_expires_at" field.
func TrialExpiresAtLT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldTrialExpiresAt, v))
}

// TrialExpiresAtLTE applies the LTE predicate on the "trial_expires_at" field.
func TrialExpiresAtLTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldTrialExpiresAt, v))
}

// TrialExpiresAtIsNil applies the IsNil predicate on the "trial_expires_at" field.
func TrialExpiresAtIsNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIsNull(FieldTrialExpiresAt))
}

// TrialExpiresAtNotNil applies the NotNil predicate on the "trial_expires_at" field.
func TrialExpiresAtNotNil() predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotNull(FieldTrialExpiresAt))
}

// RetainedAtEQ applies the EQ predicate on the "retained_at" field.
func RetainedAtEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldEQ(FieldRetainedAt, v))
}

// RetainedAtNEQ applies the NEQ predicate on the "retained_at" field.
func RetainedAtNEQ(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNEQ(FieldRetainedAt, v))
}

// RetainedAtIn applies the In predicate on the "retained_at" field.
func RetainedAtIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldIn(FieldRetainedAt, vs...))
}

// RetainedAtNotIn applies the NotIn predicate on the "retained_at" field.
func RetainedAtNotIn(vs ...time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldNotIn(FieldRetainedAt, vs...))
}

// RetainedAtGT applies the GT predicate on the "retained_at" field.
func RetainedAtGT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGT(FieldRetainedAt, v))
}

// RetainedAtGTE applies the GTE predicate on the "retained_at" field.
func RetainedAtGTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldGTE(FieldRetainedAt, v))
}

// RetainedAtLT applies the LT predicate on the "retained_at" field.
func RetainedAtLT(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLT(FieldRetainedAt, v))
}

// RetainedAtLTE applies the LTE predicate on the "retained_at" field.
func RetainedAtLTE(v time.Time) predicate.BillingRetention {
	return predicate.BillingRetention(sql.FieldLTE(FieldRetainedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BillingRetention) predicate.BillingRetention {
	return predicate.BillingRetention(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BillingRetention) predicate.BillingRetention {
	return predicate.BillingRetention(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BillingRetention) predicate.BillingRetention {
	return predicate.BillingRetention(sql.NotPredicates(p))
}
