// Code generated by ent, DO NOT EDIT.

package accountdeletionchallenge

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldMethod, v))
}

// BaselineAuthTime applies equality check predicate on the "baseline_auth_time" field. It's identical to BaselineAuthTimeEQ.
func BaselineAuthTime(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldBaselineAuthTime, v))
}

// MfaRequired applies equality check predicate on the "mfa_required" field. It's identical to MfaRequiredEQ.
func MfaRequired(v bool) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldMfaRequired, v))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldCodeHash, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldTokenHash, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldAttempts, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldVerifiedAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldUpdatedAt, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContainsFold(FieldMethod, v))
}

// BaselineAuthTimeEQ applies the EQ predicate on the "baseline_auth_time" field.
func BaselineAuthTimeEQ(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldBaselineAuthTime, v))
}

// BaselineAuthTimeNEQ applies the NEQ predicate on the "baseline_auth_time" field.
func BaselineAuthTimeNEQ(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldBaselineAuthTime, v))
}

// BaselineAuthTimeIn applies the In predicate on the "baseline_auth_time" field.
func BaselineAuthTimeIn(vs ...int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldBaselineAuthTime, vs...))
}

// BaselineAuthTimeNotIn applies the NotIn predicate on the "baseline_auth_time" field.
func BaselineAuthTimeNotIn(vs ...int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldBaselineAuthTime, vs...))
}

// BaselineAuthTimeGT applies the GT predicate on the "baseline_auth_time" field.
func BaselineAuthTimeGT(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldBaselineAuthTime, v))
}

// BaselineAuthTimeGTE applies the GTE predicate on the "baseline_auth_time" field.
func BaselineAuthTimeGTE(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldBaselineAuthTime, v))
}

// BaselineAuthTimeLT applies the LT predicate on the "baseline_auth_time" field.
func BaselineAuthTimeLT(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldBaselineAuthTime, v))
}

// BaselineAuthTimeLTE applies the LTE predicate on the "baseline_auth_time" field.
func BaselineAuthTimeLTE(v int64) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldBaselineAuthTime, v))
}

// MfaRequiredEQ applies the EQ predicate on the "mfa_required" field.
func MfaRequiredEQ(v bool) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldMfaRequired, v))
}

// MfaRequiredNEQ applies the NEQ predicate on the "mfa_required" field.
func MfaRequiredNEQ(v bool) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldMfaRequired, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashIsNil applies the IsNil predicate on the "code_hash" field.
func CodeHashIsNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIsNull(FieldCodeHash))
}

// CodeHashNotNil applies the NotNil predicate on the "code_hash" field.
func CodeHashNotNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotNull(FieldCodeHash))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContainsFold(FieldCodeHash, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashIsNil applies the IsNil predicate on the "token_hash" field.
func TokenHashIsNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIsNull(FieldTokenHash))
}

// TokenHashNotNil applies the NotNil predicate on the "token_hash" field.
func TokenHashNotNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotNull(FieldTokenHash))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldContainsFold(FieldTokenHash, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldAttempts, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldExpiresAt, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotNull(FieldVerifiedAt))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.FieldNotNull(FieldConsumedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountDeletionChallenge) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountDeletionChallenge) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountDeletionChallenge) predicate.AccountDeletionChallenge {
	return predicate.AccountDeletionChallenge(sql.NotPredicates(p))
}
