// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent"
)

// The AccountDeletionChallengeFunc type is an adapter to allow the use of ordinary
// function as AccountDeletionChallenge mutator.
type AccountDeletionChallengeFunc func(context.Context, *ent.AccountDeletionChallengeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AccountDeletionChallengeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AccountDeletionChallengeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AccountDeletionChallengeMutation", m)
}

// The ActionOutcomeFunc type is an adapter to allow the use of ordinary
// function as ActionOutcome mutator.
type ActionOutcomeFunc func(context.Context, *ent.ActionOutcomeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ActionOutcomeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ActionOutcomeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ActionOutcomeMutation", m)
}

// The ActionProposalFunc type is an adapter to allow the use of ordinary
// function as ActionProposal mutator.
type ActionProposalFunc func(context.Context, *ent.ActionProposalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ActionProposalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ActionProposalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ActionProposalMutation", m)
}

// The AgentApprovalFunc type is an adapter to allow the use of ordinary
// function as AgentApproval mutator.
type AgentApprovalFunc func(context.Context, *ent.AgentApprovalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentApprovalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentApprovalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentApprovalMutation", m)
}

// The AgentDefinitionFunc type is an adapter to allow the use of ordinary
// function as AgentDefinition mutator.
type AgentDefinitionFunc func(context.Context, *ent.AgentDefinitionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentDefinitionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentDefinitionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentDefinitionMutation", m)
}

// The AgentDefinitionHistoryFunc type is an adapter to allow the use of ordinary
// function as AgentDefinitionHistory mutator.
type AgentDefinitionHistoryFunc func(context.Context, *ent.AgentDefinitionHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentDefinitionHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentDefinitionHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentDefinitionHistoryMutation", m)
}

// The AgentSessionFunc type is an adapter to allow the use of ordinary
// function as AgentSession mutator.
type AgentSessionFunc func(context.Context, *ent.AgentSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentSessionMutation", m)
}

// The AgentSessionEventFunc type is an adapter to allow the use of ordinary
// function as AgentSessionEvent mutator.
type AgentSessionEventFunc func(context.Context, *ent.AgentSessionEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentSessionEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentSessionEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentSessionEventMutation", m)
}

// The AgentToolCallFunc type is an adapter to allow the use of ordinary
// function as AgentToolCall mutator.
type AgentToolCallFunc func(context.Context, *ent.AgentToolCallMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentToolCallFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentToolCallMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentToolCallMutation", m)
}

// The AgentToolResultBlobFunc type is an adapter to allow the use of ordinary
// function as AgentToolResultBlob mutator.
type AgentToolResultBlobFunc func(context.Context, *ent.AgentToolResultBlobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentToolResultBlobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentToolResultBlobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentToolResultBlobMutation", m)
}

// The AgentTurnFunc type is an adapter to allow the use of ordinary
// function as AgentTurn mutator.
type AgentTurnFunc func(context.Context, *ent.AgentTurnMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentTurnFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentTurnMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentTurnMutation", m)
}

// The ApprovalTokenFunc type is an adapter to allow the use of ordinary
// function as ApprovalToken mutator.
type ApprovalTokenFunc func(context.Context, *ent.ApprovalTokenMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ApprovalTokenFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ApprovalTokenMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ApprovalTokenMutation", m)
}

// The BackgroundTaskFunc type is an adapter to allow the use of ordinary
// function as BackgroundTask mutator.
type BackgroundTaskFunc func(context.Context, *ent.BackgroundTaskMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackgroundTaskFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackgroundTaskMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackgroundTaskMutation", m)
}

// The BackgroundTaskArtifactFunc type is an adapter to allow the use of ordinary
// function as BackgroundTaskArtifact mutator.
type BackgroundTaskArtifactFunc func(context.Context, *ent.BackgroundTaskArtifactMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackgroundTaskArtifactFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackgroundTaskArtifactMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackgroundTaskArtifactMutation", m)
}

// The BackgroundTaskRunFunc type is an adapter to allow the use of ordinary
// function as BackgroundTaskRun mutator.
type BackgroundTaskRunFunc func(context.Context, *ent.BackgroundTaskRunMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackgroundTaskRunFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackgroundTaskRunMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackgroundTaskRunMutation", m)
}

// The BackgroundTaskRunEventFunc type is an adapter to allow the use of ordinary
// function as BackgroundTaskRunEvent mutator.
type BackgroundTaskRunEventFunc func(context.Context, *ent.BackgroundTaskRunEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackgroundTaskRunEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackgroundTaskRunEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackgroundTaskRunEventMutation", m)
}

// The BackgroundTaskScheduleStateFunc type is an adapter to allow the use of ordinary
// function as BackgroundTaskScheduleState mutator.
type BackgroundTaskScheduleStateFunc func(context.Context, *ent.BackgroundTaskScheduleStateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BackgroundTaskScheduleStateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BackgroundTaskScheduleStateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BackgroundTaskScheduleStateMutation", m)
}

// The CaptureArtifactFunc type is an adapter to allow the use of ordinary
// function as CaptureArtifact mutator.
type CaptureArtifactFunc func(context.Context, *ent.CaptureArtifactMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CaptureArtifactFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CaptureArtifactMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CaptureArtifactMutation", m)
}

// The CloudEventFunc type is an adapter to allow the use of ordinary
// function as CloudEvent mutator.
type CloudEventFunc func(context.Context, *ent.CloudEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CloudEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CloudEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CloudEventMutation", m)
}

// The CommitmentFunc type is an adapter to allow the use of ordinary
// function as Commitment mutator.
type CommitmentFunc func(context.Context, *ent.CommitmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommitmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommitmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommitmentMutation", m)
}

// The CommitmentDependencyFunc type is an adapter to allow the use of ordinary
// function as CommitmentDependency mutator.
type CommitmentDependencyFunc func(context.Context, *ent.CommitmentDependencyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommitmentDependencyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommitmentDependencyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommitmentDependencyMutation", m)
}

// The CommitmentEventFunc type is an adapter to allow the use of ordinary
// function as CommitmentEvent mutator.
type CommitmentEventFunc func(context.Context, *ent.CommitmentEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommitmentEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommitmentEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommitmentEventMutation", m)
}

// The CommunicationAttachmentFunc type is an adapter to allow the use of ordinary
// function as CommunicationAttachment mutator.
type CommunicationAttachmentFunc func(context.Context, *ent.CommunicationAttachmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationAttachmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationAttachmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationAttachmentMutation", m)
}

// The CommunicationInteractionFunc type is an adapter to allow the use of ordinary
// function as CommunicationInteraction mutator.
type CommunicationInteractionFunc func(context.Context, *ent.CommunicationInteractionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationInteractionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationInteractionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationInteractionMutation", m)
}

// The CommunicationParticipantFunc type is an adapter to allow the use of ordinary
// function as CommunicationParticipant mutator.
type CommunicationParticipantFunc func(context.Context, *ent.CommunicationParticipantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationParticipantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationParticipantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationParticipantMutation", m)
}

// The CommunicationPrivacyPolicyFunc type is an adapter to allow the use of ordinary
// function as CommunicationPrivacyPolicy mutator.
type CommunicationPrivacyPolicyFunc func(context.Context, *ent.CommunicationPrivacyPolicyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationPrivacyPolicyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationPrivacyPolicyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationPrivacyPolicyMutation", m)
}

// The CommunicationPrivacyRuleFunc type is an adapter to allow the use of ordinary
// function as CommunicationPrivacyRule mutator.
type CommunicationPrivacyRuleFunc func(context.Context, *ent.CommunicationPrivacyRuleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationPrivacyRuleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationPrivacyRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationPrivacyRuleMutation", m)
}

// The CommunicationShareGrantFunc type is an adapter to allow the use of ordinary
// function as CommunicationShareGrant mutator.
type CommunicationShareGrantFunc func(context.Context, *ent.CommunicationShareGrantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationShareGrantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationShareGrantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationShareGrantMutation", m)
}

// The CommunicationSyncCursorFunc type is an adapter to allow the use of ordinary
// function as CommunicationSyncCursor mutator.
type CommunicationSyncCursorFunc func(context.Context, *ent.CommunicationSyncCursorMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CommunicationSyncCursorFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CommunicationSyncCursorMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CommunicationSyncCursorMutation", m)
}

// The ConnectorAuditEventFunc type is an adapter to allow the use of ordinary
// function as ConnectorAuditEvent mutator.
type ConnectorAuditEventFunc func(context.Context, *ent.ConnectorAuditEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConnectorAuditEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConnectorAuditEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConnectorAuditEventMutation", m)
}

// The ConnectorCredentialCleanupJobFunc type is an adapter to allow the use of ordinary
// function as ConnectorCredentialCleanupJob mutator.
type ConnectorCredentialCleanupJobFunc func(context.Context, *ent.ConnectorCredentialCleanupJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConnectorCredentialCleanupJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConnectorCredentialCleanupJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConnectorCredentialCleanupJobMutation", m)
}

// The ConnectorCredentialRecoveryFunc type is an adapter to allow the use of ordinary
// function as ConnectorCredentialRecovery mutator.
type ConnectorCredentialRecoveryFunc func(context.Context, *ent.ConnectorCredentialRecoveryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConnectorCredentialRecoveryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConnectorCredentialRecoveryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConnectorCredentialRecoveryMutation", m)
}

// The ConnectorRevocationJobFunc type is an adapter to allow the use of ordinary
// function as ConnectorRevocationJob mutator.
type ConnectorRevocationJobFunc func(context.Context, *ent.ConnectorRevocationJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConnectorRevocationJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConnectorRevocationJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConnectorRevocationJobMutation", m)
}

// The ConsoleResourceFunc type is an adapter to allow the use of ordinary
// function as ConsoleResource mutator.
type ConsoleResourceFunc func(context.Context, *ent.ConsoleResourceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConsoleResourceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConsoleResourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConsoleResourceMutation", m)
}

// The ConversationIntelligenceArtifactFunc type is an adapter to allow the use of ordinary
// function as ConversationIntelligenceArtifact mutator.
type ConversationIntelligenceArtifactFunc func(context.Context, *ent.ConversationIntelligenceArtifactMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ConversationIntelligenceArtifactFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ConversationIntelligenceArtifactMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ConversationIntelligenceArtifactMutation", m)
}

// The CreditLedgerFunc type is an adapter to allow the use of ordinary
// function as CreditLedger mutator.
type CreditLedgerFunc func(context.Context, *ent.CreditLedgerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CreditLedgerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CreditLedgerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CreditLedgerMutation", m)
}

// The DeletedIdentityFunc type is an adapter to allow the use of ordinary
// function as DeletedIdentity mutator.
type DeletedIdentityFunc func(context.Context, *ent.DeletedIdentityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DeletedIdentityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DeletedIdentityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DeletedIdentityMutation", m)
}

// The EntityFunc type is an adapter to allow the use of ordinary
// function as Entity mutator.
type EntityFunc func(context.Context, *ent.EntityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EntityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EntityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EntityMutation", m)
}

// The EntityIdentifierFunc type is an adapter to allow the use of ordinary
// function as EntityIdentifier mutator.
type EntityIdentifierFunc func(context.Context, *ent.EntityIdentifierMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EntityIdentifierFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EntityIdentifierMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EntityIdentifierMutation", m)
}

// The EntityResourceRefFunc type is an adapter to allow the use of ordinary
// function as EntityResourceRef mutator.
type EntityResourceRefFunc func(context.Context, *ent.EntityResourceRefMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EntityResourceRefFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EntityResourceRefMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EntityResourceRefMutation", m)
}

// The GoogleWatchFunc type is an adapter to allow the use of ordinary
// function as GoogleWatch mutator.
type GoogleWatchFunc func(context.Context, *ent.GoogleWatchMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GoogleWatchFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GoogleWatchMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GoogleWatchMutation", m)
}

// The LLMUsageFunc type is an adapter to allow the use of ordinary
// function as LLMUsage mutator.
type LLMUsageFunc func(context.Context, *ent.LLMUsageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LLMUsageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LLMUsageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LLMUsageMutation", m)
}

// The LLMUsageHistoryFunc type is an adapter to allow the use of ordinary
// function as LLMUsageHistory mutator.
type LLMUsageHistoryFunc func(context.Context, *ent.LLMUsageHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LLMUsageHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LLMUsageHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LLMUsageHistoryMutation", m)
}

// The MCPConnectionFunc type is an adapter to allow the use of ordinary
// function as MCPConnection mutator.
type MCPConnectionFunc func(context.Context, *ent.MCPConnectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MCPConnectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MCPConnectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MCPConnectionMutation", m)
}

// The MCPConnectionHistoryFunc type is an adapter to allow the use of ordinary
// function as MCPConnectionHistory mutator.
type MCPConnectionHistoryFunc func(context.Context, *ent.MCPConnectionHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MCPConnectionHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MCPConnectionHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MCPConnectionHistoryMutation", m)
}

// The MailBodyCacheFunc type is an adapter to allow the use of ordinary
// function as MailBodyCache mutator.
type MailBodyCacheFunc func(context.Context, *ent.MailBodyCacheMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MailBodyCacheFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MailBodyCacheMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MailBodyCacheMutation", m)
}

// The MailMessageMetaFunc type is an adapter to allow the use of ordinary
// function as MailMessageMeta mutator.
type MailMessageMetaFunc func(context.Context, *ent.MailMessageMetaMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MailMessageMetaFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MailMessageMetaMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MailMessageMetaMutation", m)
}

// The MailSignalFunc type is an adapter to allow the use of ordinary
// function as MailSignal mutator.
type MailSignalFunc func(context.Context, *ent.MailSignalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MailSignalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MailSignalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MailSignalMutation", m)
}

// The MailThreadFunc type is an adapter to allow the use of ordinary
// function as MailThread mutator.
type MailThreadFunc func(context.Context, *ent.MailThreadMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MailThreadFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MailThreadMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MailThreadMutation", m)
}

// The MeetingMinuteUsageFunc type is an adapter to allow the use of ordinary
// function as MeetingMinuteUsage mutator.
type MeetingMinuteUsageFunc func(context.Context, *ent.MeetingMinuteUsageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MeetingMinuteUsageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MeetingMinuteUsageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MeetingMinuteUsageMutation", m)
}

// The OAuthConnectionFunc type is an adapter to allow the use of ordinary
// function as OAuthConnection mutator.
type OAuthConnectionFunc func(context.Context, *ent.OAuthConnectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthConnectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OAuthConnectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OAuthConnectionMutation", m)
}

// The OAuthConnectionHistoryFunc type is an adapter to allow the use of ordinary
// function as OAuthConnectionHistory mutator.
type OAuthConnectionHistoryFunc func(context.Context, *ent.OAuthConnectionHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthConnectionHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OAuthConnectionHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OAuthConnectionHistoryMutation", m)
}

// The OAuthPendingFunc type is an adapter to allow the use of ordinary
// function as OAuthPending mutator.
type OAuthPendingFunc func(context.Context, *ent.OAuthPendingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OAuthPendingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OAuthPendingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OAuthPendingMutation", m)
}

// The PersonFunc type is an adapter to allow the use of ordinary
// function as Person mutator.
type PersonFunc func(context.Context, *ent.PersonMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonMutation", m)
}

// The PersonAttributeFunc type is an adapter to allow the use of ordinary
// function as PersonAttribute mutator.
type PersonAttributeFunc func(context.Context, *ent.PersonAttributeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonAttributeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonAttributeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonAttributeMutation", m)
}

// The PersonIdentityFunc type is an adapter to allow the use of ordinary
// function as PersonIdentity mutator.
type PersonIdentityFunc func(context.Context, *ent.PersonIdentityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonIdentityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonIdentityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonIdentityMutation", m)
}

// The PersonInteractionStatFunc type is an adapter to allow the use of ordinary
// function as PersonInteractionStat mutator.
type PersonInteractionStatFunc func(context.Context, *ent.PersonInteractionStatMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonInteractionStatFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonInteractionStatMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonInteractionStatMutation", m)
}

// The PersonMergeCandidateFunc type is an adapter to allow the use of ordinary
// function as PersonMergeCandidate mutator.
type PersonMergeCandidateFunc func(context.Context, *ent.PersonMergeCandidateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonMergeCandidateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonMergeCandidateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonMergeCandidateMutation", m)
}

// The PersonSuppressionFunc type is an adapter to allow the use of ordinary
// function as PersonSuppression mutator.
type PersonSuppressionFunc func(context.Context, *ent.PersonSuppressionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PersonSuppressionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PersonSuppressionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PersonSuppressionMutation", m)
}

// The PolicyDecisionSnapshotFunc type is an adapter to allow the use of ordinary
// function as PolicyDecisionSnapshot mutator.
type PolicyDecisionSnapshotFunc func(context.Context, *ent.PolicyDecisionSnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PolicyDecisionSnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PolicyDecisionSnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PolicyDecisionSnapshotMutation", m)
}

// The RelationshipFunc type is an adapter to allow the use of ordinary
// function as Relationship mutator.
type RelationshipFunc func(context.Context, *ent.RelationshipMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipMutation", m)
}

// The RelationshipAssertionFunc type is an adapter to allow the use of ordinary
// function as RelationshipAssertion mutator.
type RelationshipAssertionFunc func(context.Context, *ent.RelationshipAssertionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipAssertionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipAssertionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipAssertionMutation", m)
}

// The RelationshipAttentionItemFunc type is an adapter to allow the use of ordinary
// function as RelationshipAttentionItem mutator.
type RelationshipAttentionItemFunc func(context.Context, *ent.RelationshipAttentionItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipAttentionItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipAttentionItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipAttentionItemMutation", m)
}

// The RelationshipIdentityFunc type is an adapter to allow the use of ordinary
// function as RelationshipIdentity mutator.
type RelationshipIdentityFunc func(context.Context, *ent.RelationshipIdentityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipIdentityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipIdentityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipIdentityMutation", m)
}

// The RelationshipIdentityCandidateFunc type is an adapter to allow the use of ordinary
// function as RelationshipIdentityCandidate mutator.
type RelationshipIdentityCandidateFunc func(context.Context, *ent.RelationshipIdentityCandidateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipIdentityCandidateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipIdentityCandidateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipIdentityCandidateMutation", m)
}

// The RelationshipIdentityDecisionFunc type is an adapter to allow the use of ordinary
// function as RelationshipIdentityDecision mutator.
type RelationshipIdentityDecisionFunc func(context.Context, *ent.RelationshipIdentityDecisionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipIdentityDecisionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipIdentityDecisionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipIdentityDecisionMutation", m)
}

// The RelationshipLineageEventFunc type is an adapter to allow the use of ordinary
// function as RelationshipLineageEvent mutator.
type RelationshipLineageEventFunc func(context.Context, *ent.RelationshipLineageEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipLineageEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipLineageEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipLineageEventMutation", m)
}

// The RelationshipObservationFunc type is an adapter to allow the use of ordinary
// function as RelationshipObservation mutator.
type RelationshipObservationFunc func(context.Context, *ent.RelationshipObservationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipObservationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipObservationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipObservationMutation", m)
}

// The RelationshipParticipantFunc type is an adapter to allow the use of ordinary
// function as RelationshipParticipant mutator.
type RelationshipParticipantFunc func(context.Context, *ent.RelationshipParticipantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipParticipantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipParticipantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipParticipantMutation", m)
}

// The RelationshipProjectionJobFunc type is an adapter to allow the use of ordinary
// function as RelationshipProjectionJob mutator.
type RelationshipProjectionJobFunc func(context.Context, *ent.RelationshipProjectionJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipProjectionJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipProjectionJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipProjectionJobMutation", m)
}

// The RelationshipReviewAcknowledgementFunc type is an adapter to allow the use of ordinary
// function as RelationshipReviewAcknowledgement mutator.
type RelationshipReviewAcknowledgementFunc func(context.Context, *ent.RelationshipReviewAcknowledgementMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipReviewAcknowledgementFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipReviewAcknowledgementMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipReviewAcknowledgementMutation", m)
}

// The RelationshipSourceStatusFunc type is an adapter to allow the use of ordinary
// function as RelationshipSourceStatus mutator.
type RelationshipSourceStatusFunc func(context.Context, *ent.RelationshipSourceStatusMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipSourceStatusFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipSourceStatusMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipSourceStatusMutation", m)
}

// The RelationshipStateSnapshotFunc type is an adapter to allow the use of ordinary
// function as RelationshipStateSnapshot mutator.
type RelationshipStateSnapshotFunc func(context.Context, *ent.RelationshipStateSnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RelationshipStateSnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RelationshipStateSnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RelationshipStateSnapshotMutation", m)
}

// The RevenueActionFunc type is an adapter to allow the use of ordinary
// function as RevenueAction mutator.
type RevenueActionFunc func(context.Context, *ent.RevenueActionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueActionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueActionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueActionMutation", m)
}

// The RevenueActionRevisionFunc type is an adapter to allow the use of ordinary
// function as RevenueActionRevision mutator.
type RevenueActionRevisionFunc func(context.Context, *ent.RevenueActionRevisionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueActionRevisionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueActionRevisionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueActionRevisionMutation", m)
}

// The RevenueEvidenceFunc type is an adapter to allow the use of ordinary
// function as RevenueEvidence mutator.
type RevenueEvidenceFunc func(context.Context, *ent.RevenueEvidenceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueEvidenceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueEvidenceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueEvidenceMutation", m)
}

// The RevenueLeakScanFunc type is an adapter to allow the use of ordinary
// function as RevenueLeakScan mutator.
type RevenueLeakScanFunc func(context.Context, *ent.RevenueLeakScanMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueLeakScanFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueLeakScanMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueLeakScanMutation", m)
}

// The RevenueOutboxEventFunc type is an adapter to allow the use of ordinary
// function as RevenueOutboxEvent mutator.
type RevenueOutboxEventFunc func(context.Context, *ent.RevenueOutboxEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueOutboxEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueOutboxEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueOutboxEventMutation", m)
}

// The RevenueTrustEventFunc type is an adapter to allow the use of ordinary
// function as RevenueTrustEvent mutator.
type RevenueTrustEventFunc func(context.Context, *ent.RevenueTrustEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueTrustEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueTrustEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueTrustEventMutation", m)
}

// The RevenueWorkspaceFunc type is an adapter to allow the use of ordinary
// function as RevenueWorkspace mutator.
type RevenueWorkspaceFunc func(context.Context, *ent.RevenueWorkspaceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueWorkspaceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueWorkspaceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueWorkspaceMutation", m)
}

// The RevenueWorkspaceMemberFunc type is an adapter to allow the use of ordinary
// function as RevenueWorkspaceMember mutator.
type RevenueWorkspaceMemberFunc func(context.Context, *ent.RevenueWorkspaceMemberMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RevenueWorkspaceMemberFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RevenueWorkspaceMemberMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RevenueWorkspaceMemberMutation", m)
}

// The SubscriptionFunc type is an adapter to allow the use of ordinary
// function as Subscription mutator.
type SubscriptionFunc func(context.Context, *ent.SubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SubscriptionMutation", m)
}

// The SubscriptionHistoryFunc type is an adapter to allow the use of ordinary
// function as SubscriptionHistory mutator.
type SubscriptionHistoryFunc func(context.Context, *ent.SubscriptionHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SubscriptionHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SubscriptionHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SubscriptionHistoryMutation", m)
}

// The TenantEvidenceKeyFunc type is an adapter to allow the use of ordinary
// function as TenantEvidenceKey mutator.
type TenantEvidenceKeyFunc func(context.Context, *ent.TenantEvidenceKeyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenantEvidenceKeyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenantEvidenceKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenantEvidenceKeyMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserHistoryFunc type is an adapter to allow the use of ordinary
// function as UserHistory mutator.
type UserHistoryFunc func(context.Context, *ent.UserHistoryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserHistoryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserHistoryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserHistoryMutation", m)
}

// The UserPreferenceFunc type is an adapter to allow the use of ordinary
// function as UserPreference mutator.
type UserPreferenceFunc func(context.Context, *ent.UserPreferenceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserPreferenceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserPreferenceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserPreferenceMutation", m)
}

// The VoiceAPIKeyFunc type is an adapter to allow the use of ordinary
// function as VoiceAPIKey mutator.
type VoiceAPIKeyFunc func(context.Context, *ent.VoiceAPIKeyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f VoiceAPIKeyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.VoiceAPIKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.VoiceAPIKeyMutation", m)
}

// The VoiceSyncItemFunc type is an adapter to allow the use of ordinary
// function as VoiceSyncItem mutator.
type VoiceSyncItemFunc func(context.Context, *ent.VoiceSyncItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f VoiceSyncItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.VoiceSyncItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.VoiceSyncItemMutation", m)
}

// The WorkspaceFeatureControlFunc type is an adapter to allow the use of ordinary
// function as WorkspaceFeatureControl mutator.
type WorkspaceFeatureControlFunc func(context.Context, *ent.WorkspaceFeatureControlMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WorkspaceFeatureControlFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WorkspaceFeatureControlMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WorkspaceFeatureControlMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
