// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountDeletionChallenge is the predicate function for accountdeletionchallenge builders.
type AccountDeletionChallenge func(*sql.Selector)

// ActionOutcome is the predicate function for actionoutcome builders.
type ActionOutcome func(*sql.Selector)

// ActionProposal is the predicate function for actionproposal builders.
type ActionProposal func(*sql.Selector)

// AgentApproval is the predicate function for agentapproval builders.
type AgentApproval func(*sql.Selector)

// AgentDefinition is the predicate function for agentdefinition builders.
type AgentDefinition func(*sql.Selector)

// AgentDefinitionHistory is the predicate function for agentdefinitionhistory builders.
type AgentDefinitionHistory func(*sql.Selector)

// AgentSession is the predicate function for agentsession builders.
type AgentSession func(*sql.Selector)

// AgentSessionEvent is the predicate function for agentsessionevent builders.
type AgentSessionEvent func(*sql.Selector)

// AgentToolCall is the predicate function for agenttoolcall builders.
type AgentToolCall func(*sql.Selector)

// AgentToolResultBlob is the predicate function for agenttoolresultblob builders.
type AgentToolResultBlob func(*sql.Selector)

// AgentTurn is the predicate function for agentturn builders.
type AgentTurn func(*sql.Selector)

// ApprovalToken is the predicate function for approvaltoken builders.
type ApprovalToken func(*sql.Selector)

// BackgroundTask is the predicate function for backgroundtask builders.
type BackgroundTask func(*sql.Selector)

// BackgroundTaskArtifact is the predicate function for backgroundtaskartifact builders.
type BackgroundTaskArtifact func(*sql.Selector)

// BackgroundTaskRun is the predicate function for backgroundtaskrun builders.
type BackgroundTaskRun func(*sql.Selector)

// BackgroundTaskRunEvent is the predicate function for backgroundtaskrunevent builders.
type BackgroundTaskRunEvent func(*sql.Selector)

// BackgroundTaskScheduleState is the predicate function for backgroundtaskschedulestate builders.
type BackgroundTaskScheduleState func(*sql.Selector)

// BillingRetention is the predicate function for billingretention builders.
type BillingRetention func(*sql.Selector)

// CaptureArtifact is the predicate function for captureartifact builders.
type CaptureArtifact func(*sql.Selector)

// CloudEvent is the predicate function for cloudevent builders.
type CloudEvent func(*sql.Selector)

// Commitment is the predicate function for commitment builders.
type Commitment func(*sql.Selector)

// CommitmentDependency is the predicate function for commitmentdependency builders.
type CommitmentDependency func(*sql.Selector)

// CommitmentEvent is the predicate function for commitmentevent builders.
type CommitmentEvent func(*sql.Selector)

// CommunicationAttachment is the predicate function for communicationattachment builders.
type CommunicationAttachment func(*sql.Selector)

// CommunicationInteraction is the predicate function for communicationinteraction builders.
type CommunicationInteraction func(*sql.Selector)

// CommunicationParticipant is the predicate function for communicationparticipant builders.
type CommunicationParticipant func(*sql.Selector)

// CommunicationPrivacyPolicy is the predicate function for communicationprivacypolicy builders.
type CommunicationPrivacyPolicy func(*sql.Selector)

// CommunicationPrivacyRule is the predicate function for communicationprivacyrule builders.
type CommunicationPrivacyRule func(*sql.Selector)

// CommunicationShareGrant is the predicate function for communicationsharegrant builders.
type CommunicationShareGrant func(*sql.Selector)

// CommunicationSyncCursor is the predicate function for communicationsynccursor builders.
type CommunicationSyncCursor func(*sql.Selector)

// ConnectorAuditEvent is the predicate function for connectorauditevent builders.
type ConnectorAuditEvent func(*sql.Selector)

// ConnectorCredentialCleanupJob is the predicate function for connectorcredentialcleanupjob builders.
type ConnectorCredentialCleanupJob func(*sql.Selector)

// ConnectorCredentialRecovery is the predicate function for connectorcredentialrecovery builders.
type ConnectorCredentialRecovery func(*sql.Selector)

// ConnectorRevocationJob is the predicate function for connectorrevocationjob builders.
type ConnectorRevocationJob func(*sql.Selector)

// ConsoleResource is the predicate function for consoleresource builders.
type ConsoleResource func(*sql.Selector)

// ConversationIntelligenceArtifact is the predicate function for conversationintelligenceartifact builders.
type ConversationIntelligenceArtifact func(*sql.Selector)

// CreditLedger is the predicate function for creditledger builders.
type CreditLedger func(*sql.Selector)

// DeletedIdentity is the predicate function for deletedidentity builders.
type DeletedIdentity func(*sql.Selector)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// EntityIdentifier is the predicate function for entityidentifier builders.
type EntityIdentifier func(*sql.Selector)

// EntityResourceRef is the predicate function for entityresourceref builders.
type EntityResourceRef func(*sql.Selector)

// GoogleWatch is the predicate function for googlewatch builders.
type GoogleWatch func(*sql.Selector)

// LLMUsage is the predicate function for llmusage builders.
type LLMUsage func(*sql.Selector)

// LLMUsageHistory is the predicate function for llmusagehistory builders.
type LLMUsageHistory func(*sql.Selector)

// MCPConnection is the predicate function for mcpconnection builders.
type MCPConnection func(*sql.Selector)

// MCPConnectionHistory is the predicate function for mcpconnectionhistory builders.
type MCPConnectionHistory func(*sql.Selector)

// MailBodyCache is the predicate function for mailbodycache builders.
type MailBodyCache func(*sql.Selector)

// MailMessageMeta is the predicate function for mailmessagemeta builders.
type MailMessageMeta func(*sql.Selector)

// MailSignal is the predicate function for mailsignal builders.
type MailSignal func(*sql.Selector)

// MailThread is the predicate function for mailthread builders.
type MailThread func(*sql.Selector)

// MeetingMinuteUsage is the predicate function for meetingminuteusage builders.
type MeetingMinuteUsage func(*sql.Selector)

// OAuthConnection is the predicate function for oauthconnection builders.
type OAuthConnection func(*sql.Selector)

// OAuthConnectionHistory is the predicate function for oauthconnectionhistory builders.
type OAuthConnectionHistory func(*sql.Selector)

// OAuthPending is the predicate function for oauthpending builders.
type OAuthPending func(*sql.Selector)

// Person is the predicate function for person builders.
type Person func(*sql.Selector)

// PersonAttribute is the predicate function for personattribute builders.
type PersonAttribute func(*sql.Selector)

// PersonIdentity is the predicate function for personidentity builders.
type PersonIdentity func(*sql.Selector)

// PersonInteractionStat is the predicate function for personinteractionstat builders.
type PersonInteractionStat func(*sql.Selector)

// PersonMergeCandidate is the predicate function for personmergecandidate builders.
type PersonMergeCandidate func(*sql.Selector)

// PersonSuppression is the predicate function for personsuppression builders.
type PersonSuppression func(*sql.Selector)

// PolicyDecisionSnapshot is the predicate function for policydecisionsnapshot builders.
type PolicyDecisionSnapshot func(*sql.Selector)

// Relationship is the predicate function for relationship builders.
type Relationship func(*sql.Selector)

// RelationshipAssertion is the predicate function for relationshipassertion builders.
type RelationshipAssertion func(*sql.Selector)

// RelationshipAttentionItem is the predicate function for relationshipattentionitem builders.
type RelationshipAttentionItem func(*sql.Selector)

// RelationshipIdentity is the predicate function for relationshipidentity builders.
type RelationshipIdentity func(*sql.Selector)

// RelationshipIdentityCandidate is the predicate function for relationshipidentitycandidate builders.
type RelationshipIdentityCandidate func(*sql.Selector)

// RelationshipIdentityDecision is the predicate function for relationshipidentitydecision builders.
type RelationshipIdentityDecision func(*sql.Selector)

// RelationshipLineageEvent is the predicate function for relationshiplineageevent builders.
type RelationshipLineageEvent func(*sql.Selector)

// RelationshipObservation is the predicate function for relationshipobservation builders.
type RelationshipObservation func(*sql.Selector)

// RelationshipParticipant is the predicate function for relationshipparticipant builders.
type RelationshipParticipant func(*sql.Selector)

// RelationshipProjectionJob is the predicate function for relationshipprojectionjob builders.
type RelationshipProjectionJob func(*sql.Selector)

// RelationshipReviewAcknowledgement is the predicate function for relationshipreviewacknowledgement builders.
type RelationshipReviewAcknowledgement func(*sql.Selector)

// RelationshipSourceStatus is the predicate function for relationshipsourcestatus builders.
type RelationshipSourceStatus func(*sql.Selector)

// RelationshipStateSnapshot is the predicate function for relationshipstatesnapshot builders.
type RelationshipStateSnapshot func(*sql.Selector)

// RevenueAction is the predicate function for revenueaction builders.
type RevenueAction func(*sql.Selector)

// RevenueActionRevision is the predicate function for revenueactionrevision builders.
type RevenueActionRevision func(*sql.Selector)

// RevenueEvidence is the predicate function for revenueevidence builders.
type RevenueEvidence func(*sql.Selector)

// RevenueLeakScan is the predicate function for revenueleakscan builders.
type RevenueLeakScan func(*sql.Selector)

// RevenueOutboxEvent is the predicate function for revenueoutboxevent builders.
type RevenueOutboxEvent func(*sql.Selector)

// RevenueTrustEvent is the predicate function for revenuetrustevent builders.
type RevenueTrustEvent func(*sql.Selector)

// RevenueWorkspace is the predicate function for revenueworkspace builders.
type RevenueWorkspace func(*sql.Selector)

// RevenueWorkspaceMember is the predicate function for revenueworkspacemember builders.
type RevenueWorkspaceMember func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// SubscriptionHistory is the predicate function for subscriptionhistory builders.
type SubscriptionHistory func(*sql.Selector)

// TenantEvidenceKey is the predicate function for tenantevidencekey builders.
type TenantEvidenceKey func(*sql.Selector)

// TermsAssent is the predicate function for termsassent builders.
type TermsAssent func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserHistory is the predicate function for userhistory builders.
type UserHistory func(*sql.Selector)

// UserPreference is the predicate function for userpreference builders.
type UserPreference func(*sql.Selector)

// VoiceAPIKey is the predicate function for voiceapikey builders.
type VoiceAPIKey func(*sql.Selector)

// VoiceSyncItem is the predicate function for voicesyncitem builders.
type VoiceSyncItem func(*sql.Selector)

// WorkspaceFeatureControl is the predicate function for workspacefeaturecontrol builders.
type WorkspaceFeatureControl func(*sql.Selector)
