// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// WorkosUserID applies equality check predicate on the "workos_user_id" field. It's identical to WorkosUserIDEQ.
func WorkosUserID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkosUserID, v))
}

// WorkosOrgID applies equality check predicate on the "workos_org_id" field. It's identical to WorkosOrgIDEQ.
func WorkosOrgID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkosOrgID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// WorkosUserIDEQ applies the EQ predicate on the "workos_user_id" field.
func WorkosUserIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkosUserID, v))
}

// WorkosUserIDNEQ applies the NEQ predicate on the "workos_user_id" field.
func WorkosUserIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWorkosUserID, v))
}

// WorkosUserIDIn applies the In predicate on the "workos_user_id" field.
func WorkosUserIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldWorkosUserID, vs...))
}

// WorkosUserIDNotIn applies the NotIn predicate on the "workos_user_id" field.
func WorkosUserIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWorkosUserID, vs...))
}

// WorkosUserIDGT applies the GT predicate on the "workos_user_id" field.
func WorkosUserIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldWorkosUserID, v))
}

// WorkosUserIDGTE applies the GTE predicate on the "workos_user_id" field.
func WorkosUserIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWorkosUserID, v))
}

// WorkosUserIDLT applies the LT predicate on the "workos_user_id" field.
func WorkosUserIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldWorkosUserID, v))
}

// WorkosUserIDLTE applies the LTE predicate on the "workos_user_id" field.
func WorkosUserIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWorkosUserID, v))
}

// WorkosUserIDContains applies the Contains predicate on the "workos_user_id" field.
func WorkosUserIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldWorkosUserID, v))
}

// WorkosUserIDHasPrefix applies the HasPrefix predicate on the "workos_user_id" field.
func WorkosUserIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldWorkosUserID, v))
}

// WorkosUserIDHasSuffix applies the HasSuffix predicate on the "workos_user_id" field.
func WorkosUserIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldWorkosUserID, v))
}

// WorkosUserIDEqualFold applies the EqualFold predicate on the "workos_user_id" field.
func WorkosUserIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldWorkosUserID, v))
}

// WorkosUserIDContainsFold applies the ContainsFold predicate on the "workos_user_id" field.
func WorkosUserIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldWorkosUserID, v))
}

// WorkosOrgIDEQ applies the EQ predicate on the "workos_org_id" field.
func WorkosOrgIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkosOrgID, v))
}

// WorkosOrgIDNEQ applies the NEQ predicate on the "workos_org_id" field.
func WorkosOrgIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWorkosOrgID, v))
}

// WorkosOrgIDIn applies the In predicate on the "workos_org_id" field.
func WorkosOrgIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldWorkosOrgID, vs...))
}

// WorkosOrgIDNotIn applies the NotIn predicate on the "workos_org_id" field.
func WorkosOrgIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWorkosOrgID, vs...))
}

// WorkosOrgIDGT applies the GT predicate on the "workos_org_id" field.
func WorkosOrgIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldWorkosOrgID, v))
}

// WorkosOrgIDGTE applies the GTE predicate on the "workos_org_id" field.
func WorkosOrgIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWorkosOrgID, v))
}

// WorkosOrgIDLT applies the LT predicate on the "workos_org_id" field.
func WorkosOrgIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldWorkosOrgID, v))
}

// WorkosOrgIDLTE applies the LTE predicate on the "workos_org_id" field.
func WorkosOrgIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWorkosOrgID, v))
}

// WorkosOrgIDContains applies the Contains predicate on the "workos_org_id" field.
func WorkosOrgIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldWorkosOrgID, v))
}

// WorkosOrgIDHasPrefix applies the HasPrefix predicate on the "workos_org_id" field.
func WorkosOrgIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldWorkosOrgID, v))
}

// WorkosOrgIDHasSuffix applies the HasSuffix predicate on the "workos_org_id" field.
func WorkosOrgIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldWorkosOrgID, v))
}

// WorkosOrgIDIsNil applies the IsNil predicate on the "workos_org_id" field.
func WorkosOrgIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldWorkosOrgID))
}

// WorkosOrgIDNotNil applies the NotNil predicate on the "workos_org_id" field.
func WorkosOrgIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldWorkosOrgID))
}

// WorkosOrgIDEqualFold applies the EqualFold predicate on the "workos_org_id" field.
func WorkosOrgIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldWorkosOrgID, v))
}

// WorkosOrgIDContainsFold applies the ContainsFold predicate on the "workos_org_id" field.
func WorkosOrgIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldWorkosOrgID, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.Subscription) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerEntries applies the HasEdge predicate on the "ledger_entries" edge.
func HasLedgerEntries() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerEntriesWith applies the HasEdge predicate on the "ledger_entries" edge with a given conditions (other predicates).
func HasLedgerEntriesWith(preds ...predicate.CreditLedger) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newLedgerEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMeetingMinuteUsages applies the HasEdge predicate on the "meeting_minute_usages" edge.
func HasMeetingMinuteUsages() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MeetingMinuteUsagesTable, MeetingMinuteUsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMeetingMinuteUsagesWith applies the HasEdge predicate on the "meeting_minute_usages" edge with a given conditions (other predicates).
func HasMeetingMinuteUsagesWith(preds ...predicate.MeetingMinuteUsage) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMeetingMinuteUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVoiceAPIKeys applies the HasEdge predicate on the "voice_api_keys" edge.
func HasVoiceAPIKeys() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VoiceAPIKeysTable, VoiceAPIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVoiceAPIKeysWith applies the HasEdge predicate on the "voice_api_keys" edge with a given conditions (other predicates).
func HasVoiceAPIKeysWith(preds ...predicate.VoiceAPIKey) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newVoiceAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVoiceSyncItems applies the HasEdge predicate on the "voice_sync_items" edge.
func HasVoiceSyncItems() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VoiceSyncItemsTable, VoiceSyncItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVoiceSyncItemsWith applies the HasEdge predicate on the "voice_sync_items" edge with a given conditions (other predicates).
func HasVoiceSyncItemsWith(preds ...predicate.VoiceSyncItem) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newVoiceSyncItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCaptureArtifacts applies the HasEdge predicate on the "capture_artifacts" edge.
func HasCaptureArtifacts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CaptureArtifactsTable, CaptureArtifactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCaptureArtifactsWith applies the HasEdge predicate on the "capture_artifacts" edge with a given conditions (other predicates).
func HasCaptureArtifactsWith(preds ...predicate.CaptureArtifact) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCaptureArtifactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLlmUsages applies the HasEdge predicate on the "llm_usages" edge.
func HasLlmUsages() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LlmUsagesTable, LlmUsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLlmUsagesWith applies the HasEdge predicate on the "llm_usages" edge with a given conditions (other predicates).
func HasLlmUsagesWith(preds ...predicate.LLMUsage) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newLlmUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOauthConnections applies the HasEdge predicate on the "oauth_connections" edge.
func HasOauthConnections() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OauthConnectionsTable, OauthConnectionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOauthConnectionsWith applies the HasEdge predicate on the "oauth_connections" edge with a given conditions (other predicates).
func HasOauthConnectionsWith(preds ...predicate.OAuthConnection) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newOauthConnectionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMcpConnections applies the HasEdge predicate on the "mcp_connections" edge.
func HasMcpConnections() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, McpConnectionsTable, McpConnectionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMcpConnectionsWith applies the HasEdge predicate on the "mcp_connections" edge with a given conditions (other predicates).
func HasMcpConnectionsWith(preds ...predicate.MCPConnection) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMcpConnectionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConnectorAuditEvents applies the HasEdge predicate on the "connector_audit_events" edge.
func HasConnectorAuditEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConnectorAuditEventsTable, ConnectorAuditEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectorAuditEventsWith applies the HasEdge predicate on the "connector_audit_events" edge with a given conditions (other predicates).
func HasConnectorAuditEventsWith(preds ...predicate.ConnectorAuditEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newConnectorAuditEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackgroundTasks applies the HasEdge predicate on the "background_tasks" edge.
func HasBackgroundTasks() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BackgroundTasksTable, BackgroundTasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackgroundTasksWith applies the HasEdge predicate on the "background_tasks" edge with a given conditions (other predicates).
func HasBackgroundTasksWith(preds ...predicate.BackgroundTask) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBackgroundTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackgroundTaskArtifacts applies the HasEdge predicate on the "background_task_artifacts" edge.
func HasBackgroundTaskArtifacts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BackgroundTaskArtifactsTable, BackgroundTaskArtifactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackgroundTaskArtifactsWith applies the HasEdge predicate on the "background_task_artifacts" edge with a given conditions (other predicates).
func HasBackgroundTaskArtifactsWith(preds ...predicate.BackgroundTaskArtifact) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBackgroundTaskArtifactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackgroundTaskRuns applies the HasEdge predicate on the "background_task_runs" edge.
func HasBackgroundTaskRuns() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BackgroundTaskRunsTable, BackgroundTaskRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackgroundTaskRunsWith applies the HasEdge predicate on the "background_task_runs" edge with a given conditions (other predicates).
func HasBackgroundTaskRunsWith(preds ...predicate.BackgroundTaskRun) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBackgroundTaskRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackgroundTaskRunEvents applies the HasEdge predicate on the "background_task_run_events" edge.
func HasBackgroundTaskRunEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BackgroundTaskRunEventsTable, BackgroundTaskRunEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackgroundTaskRunEventsWith applies the HasEdge predicate on the "background_task_run_events" edge with a given conditions (other predicates).
func HasBackgroundTaskRunEventsWith(preds ...predicate.BackgroundTaskRunEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBackgroundTaskRunEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackgroundTaskScheduleStates applies the HasEdge predicate on the "background_task_schedule_states" edge.
func HasBackgroundTaskScheduleStates() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BackgroundTaskScheduleStatesTable, BackgroundTaskScheduleStatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackgroundTaskScheduleStatesWith applies the HasEdge predicate on the "background_task_schedule_states" edge with a given conditions (other predicates).
func HasBackgroundTaskScheduleStatesWith(preds ...predicate.BackgroundTaskScheduleState) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newBackgroundTaskScheduleStatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCloudEvents applies the HasEdge predicate on the "cloud_events" edge.
func HasCloudEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CloudEventsTable, CloudEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCloudEventsWith applies the HasEdge predicate on the "cloud_events" edge with a given conditions (other predicates).
func HasCloudEventsWith(preds ...predicate.CloudEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCloudEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGoogleWatches applies the HasEdge predicate on the "google_watches" edge.
func HasGoogleWatches() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GoogleWatchesTable, GoogleWatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGoogleWatchesWith applies the HasEdge predicate on the "google_watches" edge with a given conditions (other predicates).
func HasGoogleWatchesWith(preds ...predicate.GoogleWatch) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newGoogleWatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentDefinitions applies the HasEdge predicate on the "agent_definitions" edge.
func HasAgentDefinitions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentDefinitionsTable, AgentDefinitionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentDefinitionsWith applies the HasEdge predicate on the "agent_definitions" edge with a given conditions (other predicates).
func HasAgentDefinitionsWith(preds ...predicate.AgentDefinition) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentDefinitionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentSessions applies the HasEdge predicate on the "agent_sessions" edge.
func HasAgentSessions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentSessionsTable, AgentSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentSessionsWith applies the HasEdge predicate on the "agent_sessions" edge with a given conditions (other predicates).
func HasAgentSessionsWith(preds ...predicate.AgentSession) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentTurns applies the HasEdge predicate on the "agent_turns" edge.
func HasAgentTurns() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentTurnsTable, AgentTurnsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentTurnsWith applies the HasEdge predicate on the "agent_turns" edge with a given conditions (other predicates).
func HasAgentTurnsWith(preds ...predicate.AgentTurn) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentTurnsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentSessionEvents applies the HasEdge predicate on the "agent_session_events" edge.
func HasAgentSessionEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentSessionEventsTable, AgentSessionEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentSessionEventsWith applies the HasEdge predicate on the "agent_session_events" edge with a given conditions (other predicates).
func HasAgentSessionEventsWith(preds ...predicate.AgentSessionEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentSessionEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentToolCalls applies the HasEdge predicate on the "agent_tool_calls" edge.
func HasAgentToolCalls() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentToolCallsTable, AgentToolCallsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentToolCallsWith applies the HasEdge predicate on the "agent_tool_calls" edge with a given conditions (other predicates).
func HasAgentToolCallsWith(preds ...predicate.AgentToolCall) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentToolCallsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentApprovals applies the HasEdge predicate on the "agent_approvals" edge.
func HasAgentApprovals() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentApprovalsTable, AgentApprovalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentApprovalsWith applies the HasEdge predicate on the "agent_approvals" edge with a given conditions (other predicates).
func HasAgentApprovalsWith(preds ...predicate.AgentApproval) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentApprovalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentToolResultBlobs applies the HasEdge predicate on the "agent_tool_result_blobs" edge.
func HasAgentToolResultBlobs() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AgentToolResultBlobsTable, AgentToolResultBlobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentToolResultBlobsWith applies the HasEdge predicate on the "agent_tool_result_blobs" edge with a given conditions (other predicates).
func HasAgentToolResultBlobsWith(preds ...predicate.AgentToolResultBlob) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAgentToolResultBlobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueWorkspaces applies the HasEdge predicate on the "revenue_workspaces" edge.
func HasRevenueWorkspaces() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueWorkspacesTable, RevenueWorkspacesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueWorkspacesWith applies the HasEdge predicate on the "revenue_workspaces" edge with a given conditions (other predicates).
func HasRevenueWorkspacesWith(preds ...predicate.RevenueWorkspace) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueWorkspacesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueWorkspaceMembers applies the HasEdge predicate on the "revenue_workspace_members" edge.
func HasRevenueWorkspaceMembers() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueWorkspaceMembersTable, RevenueWorkspaceMembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueWorkspaceMembersWith applies the HasEdge predicate on the "revenue_workspace_members" edge with a given conditions (other predicates).
func HasRevenueWorkspaceMembersWith(preds ...predicate.RevenueWorkspaceMember) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueWorkspaceMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationships applies the HasEdge predicate on the "relationships" edge.
func HasRelationships() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipsTable, RelationshipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipsWith applies the HasEdge predicate on the "relationships" edge with a given conditions (other predicates).
func HasRelationshipsWith(preds ...predicate.Relationship) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueEvidences applies the HasEdge predicate on the "revenue_evidences" edge.
func HasRevenueEvidences() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueEvidencesTable, RevenueEvidencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueEvidencesWith applies the HasEdge predicate on the "revenue_evidences" edge with a given conditions (other predicates).
func HasRevenueEvidencesWith(preds ...predicate.RevenueEvidence) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueEvidencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommitments applies the HasEdge predicate on the "commitments" edge.
func HasCommitments() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommitmentsTable, CommitmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommitmentsWith applies the HasEdge predicate on the "commitments" edge with a given conditions (other predicates).
func HasCommitmentsWith(preds ...predicate.Commitment) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommitmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommitmentEvents applies the HasEdge predicate on the "commitment_events" edge.
func HasCommitmentEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommitmentEventsTable, CommitmentEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommitmentEventsWith applies the HasEdge predicate on the "commitment_events" edge with a given conditions (other predicates).
func HasCommitmentEventsWith(preds ...predicate.CommitmentEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommitmentEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommitmentDependencies applies the HasEdge predicate on the "commitment_dependencies" edge.
func HasCommitmentDependencies() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommitmentDependenciesTable, CommitmentDependenciesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommitmentDependenciesWith applies the HasEdge predicate on the "commitment_dependencies" edge with a given conditions (other predicates).
func HasCommitmentDependenciesWith(preds ...predicate.CommitmentDependency) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommitmentDependenciesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConversationIntelligenceArtifacts applies the HasEdge predicate on the "conversation_intelligence_artifacts" edge.
func HasConversationIntelligenceArtifacts() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConversationIntelligenceArtifactsTable, ConversationIntelligenceArtifactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConversationIntelligenceArtifactsWith applies the HasEdge predicate on the "conversation_intelligence_artifacts" edge with a given conditions (other predicates).
func HasConversationIntelligenceArtifactsWith(preds ...predicate.ConversationIntelligenceArtifact) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newConversationIntelligenceArtifactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueActions applies the HasEdge predicate on the "revenue_actions" edge.
func HasRevenueActions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueActionsTable, RevenueActionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueActionsWith applies the HasEdge predicate on the "revenue_actions" edge with a given conditions (other predicates).
func HasRevenueActionsWith(preds ...predicate.RevenueAction) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueActionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueActionRevisions applies the HasEdge predicate on the "revenue_action_revisions" edge.
func HasRevenueActionRevisions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueActionRevisionsTable, RevenueActionRevisionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueActionRevisionsWith applies the HasEdge predicate on the "revenue_action_revisions" edge with a given conditions (other predicates).
func HasRevenueActionRevisionsWith(preds ...predicate.RevenueActionRevision) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueActionRevisionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPolicyDecisionSnapshots applies the HasEdge predicate on the "policy_decision_snapshots" edge.
func HasPolicyDecisionSnapshots() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PolicyDecisionSnapshotsTable, PolicyDecisionSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPolicyDecisionSnapshotsWith applies the HasEdge predicate on the "policy_decision_snapshots" edge with a given conditions (other predicates).
func HasPolicyDecisionSnapshotsWith(preds ...predicate.PolicyDecisionSnapshot) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPolicyDecisionSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActionOutcomes applies the HasEdge predicate on the "action_outcomes" edge.
func HasActionOutcomes() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActionOutcomesTable, ActionOutcomesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionOutcomesWith applies the HasEdge predicate on the "action_outcomes" edge with a given conditions (other predicates).
func HasActionOutcomesWith(preds ...predicate.ActionOutcome) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newActionOutcomesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueOutboxEvents applies the HasEdge predicate on the "revenue_outbox_events" edge.
func HasRevenueOutboxEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueOutboxEventsTable, RevenueOutboxEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueOutboxEventsWith applies the HasEdge predicate on the "revenue_outbox_events" edge with a given conditions (other predicates).
func HasRevenueOutboxEventsWith(preds ...predicate.RevenueOutboxEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueOutboxEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueLeakScans applies the HasEdge predicate on the "revenue_leak_scans" edge.
func HasRevenueLeakScans() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueLeakScansTable, RevenueLeakScansColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueLeakScansWith applies the HasEdge predicate on the "revenue_leak_scans" edge with a given conditions (other predicates).
func HasRevenueLeakScansWith(preds ...predicate.RevenueLeakScan) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueLeakScansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMailThreads applies the HasEdge predicate on the "mail_threads" edge.
func HasMailThreads() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MailThreadsTable, MailThreadsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMailThreadsWith applies the HasEdge predicate on the "mail_threads" edge with a given conditions (other predicates).
func HasMailThreadsWith(preds ...predicate.MailThread) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMailThreadsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMailMessageMetas applies the HasEdge predicate on the "mail_message_metas" edge.
func HasMailMessageMetas() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MailMessageMetasTable, MailMessageMetasColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMailMessageMetasWith applies the HasEdge predicate on the "mail_message_metas" edge with a given conditions (other predicates).
func HasMailMessageMetasWith(preds ...predicate.MailMessageMeta) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMailMessageMetasStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMailBodyCaches applies the HasEdge predicate on the "mail_body_caches" edge.
func HasMailBodyCaches() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MailBodyCachesTable, MailBodyCachesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMailBodyCachesWith applies the HasEdge predicate on the "mail_body_caches" edge with a given conditions (other predicates).
func HasMailBodyCachesWith(preds ...predicate.MailBodyCache) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMailBodyCachesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMailSignals applies the HasEdge predicate on the "mail_signals" edge.
func HasMailSignals() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MailSignalsTable, MailSignalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMailSignalsWith applies the HasEdge predicate on the "mail_signals" edge with a given conditions (other predicates).
func HasMailSignalsWith(preds ...predicate.MailSignal) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMailSignalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnedCommunicationInteractions applies the HasEdge predicate on the "owned_communication_interactions" edge.
func HasOwnedCommunicationInteractions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OwnedCommunicationInteractionsTable, OwnedCommunicationInteractionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedCommunicationInteractionsWith applies the HasEdge predicate on the "owned_communication_interactions" edge with a given conditions (other predicates).
func HasOwnedCommunicationInteractionsWith(preds ...predicate.CommunicationInteraction) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newOwnedCommunicationInteractionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommunicationSyncCursors applies the HasEdge predicate on the "communication_sync_cursors" edge.
func HasCommunicationSyncCursors() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommunicationSyncCursorsTable, CommunicationSyncCursorsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommunicationSyncCursorsWith applies the HasEdge predicate on the "communication_sync_cursors" edge with a given conditions (other predicates).
func HasCommunicationSyncCursorsWith(preds ...predicate.CommunicationSyncCursor) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommunicationSyncCursorsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommunicationPrivacyPolicies applies the HasEdge predicate on the "communication_privacy_policies" edge.
func HasCommunicationPrivacyPolicies() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommunicationPrivacyPoliciesTable, CommunicationPrivacyPoliciesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommunicationPrivacyPoliciesWith applies the HasEdge predicate on the "communication_privacy_policies" edge with a given conditions (other predicates).
func HasCommunicationPrivacyPoliciesWith(preds ...predicate.CommunicationPrivacyPolicy) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommunicationPrivacyPoliciesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCommunicationPrivacyRules applies the HasEdge predicate on the "communication_privacy_rules" edge.
func HasCommunicationPrivacyRules() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommunicationPrivacyRulesTable, CommunicationPrivacyRulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommunicationPrivacyRulesWith applies the HasEdge predicate on the "communication_privacy_rules" edge with a given conditions (other predicates).
func HasCommunicationPrivacyRulesWith(preds ...predicate.CommunicationPrivacyRule) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newCommunicationPrivacyRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwnedCommunicationShareGrants applies the HasEdge predicate on the "owned_communication_share_grants" edge.
func HasOwnedCommunicationShareGrants() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OwnedCommunicationShareGrantsTable, OwnedCommunicationShareGrantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnedCommunicationShareGrantsWith applies the HasEdge predicate on the "owned_communication_share_grants" edge with a given conditions (other predicates).
func HasOwnedCommunicationShareGrantsWith(preds ...predicate.CommunicationShareGrant) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newOwnedCommunicationShareGrantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReceivedCommunicationShareGrants applies the HasEdge predicate on the "received_communication_share_grants" edge.
func HasReceivedCommunicationShareGrants() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReceivedCommunicationShareGrantsTable, ReceivedCommunicationShareGrantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReceivedCommunicationShareGrantsWith applies the HasEdge predicate on the "received_communication_share_grants" edge with a given conditions (other predicates).
func HasReceivedCommunicationShareGrantsWith(preds ...predicate.CommunicationShareGrant) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newReceivedCommunicationShareGrantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipParticipants applies the HasEdge predicate on the "relationship_participants" edge.
func HasRelationshipParticipants() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipParticipantsTable, RelationshipParticipantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipParticipantsWith applies the HasEdge predicate on the "relationship_participants" edge with a given conditions (other predicates).
func HasRelationshipParticipantsWith(preds ...predicate.RelationshipParticipant) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipParticipantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipIdentities applies the HasEdge predicate on the "relationship_identities" edge.
func HasRelationshipIdentities() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipIdentitiesTable, RelationshipIdentitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipIdentitiesWith applies the HasEdge predicate on the "relationship_identities" edge with a given conditions (other predicates).
func HasRelationshipIdentitiesWith(preds ...predicate.RelationshipIdentity) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipIdentitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipPersons applies the HasEdge predicate on the "relationship_persons" edge.
func HasRelationshipPersons() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipPersonsTable, RelationshipPersonsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipPersonsWith applies the HasEdge predicate on the "relationship_persons" edge with a given conditions (other predicates).
func HasRelationshipPersonsWith(preds ...predicate.Person) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipPersonsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPersonIdentities applies the HasEdge predicate on the "person_identities" edge.
func HasPersonIdentities() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonIdentitiesTable, PersonIdentitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonIdentitiesWith applies the HasEdge predicate on the "person_identities" edge with a given conditions (other predicates).
func HasPersonIdentitiesWith(preds ...predicate.PersonIdentity) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPersonIdentitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPersonSuppressions applies the HasEdge predicate on the "person_suppressions" edge.
func HasPersonSuppressions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonSuppressionsTable, PersonSuppressionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonSuppressionsWith applies the HasEdge predicate on the "person_suppressions" edge with a given conditions (other predicates).
func HasPersonSuppressionsWith(preds ...predicate.PersonSuppression) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPersonSuppressionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPersonAttributes applies the HasEdge predicate on the "person_attributes" edge.
func HasPersonAttributes() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonAttributesTable, PersonAttributesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonAttributesWith applies the HasEdge predicate on the "person_attributes" edge with a given conditions (other predicates).
func HasPersonAttributesWith(preds ...predicate.PersonAttribute) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPersonAttributesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPersonMergeCandidates applies the HasEdge predicate on the "person_merge_candidates" edge.
func HasPersonMergeCandidates() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PersonMergeCandidatesTable, PersonMergeCandidatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonMergeCandidatesWith applies the HasEdge predicate on the "person_merge_candidates" edge with a given conditions (other predicates).
func HasPersonMergeCandidatesWith(preds ...predicate.PersonMergeCandidate) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPersonMergeCandidatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipProjectionJobs applies the HasEdge predicate on the "relationship_projection_jobs" edge.
func HasRelationshipProjectionJobs() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipProjectionJobsTable, RelationshipProjectionJobsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipProjectionJobsWith applies the HasEdge predicate on the "relationship_projection_jobs" edge with a given conditions (other predicates).
func HasRelationshipProjectionJobsWith(preds ...predicate.RelationshipProjectionJob) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipProjectionJobsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenantEvidenceKeys applies the HasEdge predicate on the "tenant_evidence_keys" edge.
func HasTenantEvidenceKeys() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TenantEvidenceKeysTable, TenantEvidenceKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantEvidenceKeysWith applies the HasEdge predicate on the "tenant_evidence_keys" edge with a given conditions (other predicates).
func HasTenantEvidenceKeysWith(preds ...predicate.TenantEvidenceKey) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTenantEvidenceKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspaceFeatureControls applies the HasEdge predicate on the "workspace_feature_controls" edge.
func HasWorkspaceFeatureControls() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkspaceFeatureControlsTable, WorkspaceFeatureControlsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceFeatureControlsWith applies the HasEdge predicate on the "workspace_feature_controls" edge with a given conditions (other predicates).
func HasWorkspaceFeatureControlsWith(preds ...predicate.WorkspaceFeatureControl) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newWorkspaceFeatureControlsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRevenueTrustEvents applies the HasEdge predicate on the "revenue_trust_events" edge.
func HasRevenueTrustEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RevenueTrustEventsTable, RevenueTrustEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRevenueTrustEventsWith applies the HasEdge predicate on the "revenue_trust_events" edge with a given conditions (other predicates).
func HasRevenueTrustEventsWith(preds ...predicate.RevenueTrustEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRevenueTrustEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipIdentityCandidates applies the HasEdge predicate on the "relationship_identity_candidates" edge.
func HasRelationshipIdentityCandidates() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipIdentityCandidatesTable, RelationshipIdentityCandidatesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipIdentityCandidatesWith applies the HasEdge predicate on the "relationship_identity_candidates" edge with a given conditions (other predicates).
func HasRelationshipIdentityCandidatesWith(preds ...predicate.RelationshipIdentityCandidate) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipIdentityCandidatesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipLineageEvents applies the HasEdge predicate on the "relationship_lineage_events" edge.
func HasRelationshipLineageEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipLineageEventsTable, RelationshipLineageEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipLineageEventsWith applies the HasEdge predicate on the "relationship_lineage_events" edge with a given conditions (other predicates).
func HasRelationshipLineageEventsWith(preds ...predicate.RelationshipLineageEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipLineageEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipIdentityDecisions applies the HasEdge predicate on the "relationship_identity_decisions" edge.
func HasRelationshipIdentityDecisions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipIdentityDecisionsTable, RelationshipIdentityDecisionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipIdentityDecisionsWith applies the HasEdge predicate on the "relationship_identity_decisions" edge with a given conditions (other predicates).
func HasRelationshipIdentityDecisionsWith(preds ...predicate.RelationshipIdentityDecision) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipIdentityDecisionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipReviewAcknowledgements applies the HasEdge predicate on the "relationship_review_acknowledgements" edge.
func HasRelationshipReviewAcknowledgements() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipReviewAcknowledgementsTable, RelationshipReviewAcknowledgementsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipReviewAcknowledgementsWith applies the HasEdge predicate on the "relationship_review_acknowledgements" edge with a given conditions (other predicates).
func HasRelationshipReviewAcknowledgementsWith(preds ...predicate.RelationshipReviewAcknowledgement) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipReviewAcknowledgementsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipAttentionItems applies the HasEdge predicate on the "relationship_attention_items" edge.
func HasRelationshipAttentionItems() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipAttentionItemsTable, RelationshipAttentionItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipAttentionItemsWith applies the HasEdge predicate on the "relationship_attention_items" edge with a given conditions (other predicates).
func HasRelationshipAttentionItemsWith(preds ...predicate.RelationshipAttentionItem) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipAttentionItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipObservations applies the HasEdge predicate on the "relationship_observations" edge.
func HasRelationshipObservations() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipObservationsTable, RelationshipObservationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipObservationsWith applies the HasEdge predicate on the "relationship_observations" edge with a given conditions (other predicates).
func HasRelationshipObservationsWith(preds ...predicate.RelationshipObservation) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipObservationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipAssertions applies the HasEdge predicate on the "relationship_assertions" edge.
func HasRelationshipAssertions() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipAssertionsTable, RelationshipAssertionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipAssertionsWith applies the HasEdge predicate on the "relationship_assertions" edge with a given conditions (other predicates).
func HasRelationshipAssertionsWith(preds ...predicate.RelationshipAssertion) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipAssertionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipStateSnapshots applies the HasEdge predicate on the "relationship_state_snapshots" edge.
func HasRelationshipStateSnapshots() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipStateSnapshotsTable, RelationshipStateSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipStateSnapshotsWith applies the HasEdge predicate on the "relationship_state_snapshots" edge with a given conditions (other predicates).
func HasRelationshipStateSnapshotsWith(preds ...predicate.RelationshipStateSnapshot) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipStateSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelationshipSourceStatuses applies the HasEdge predicate on the "relationship_source_statuses" edge.
func HasRelationshipSourceStatuses() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RelationshipSourceStatusesTable, RelationshipSourceStatusesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelationshipSourceStatusesWith applies the HasEdge predicate on the "relationship_source_statuses" edge with a given conditions (other predicates).
func HasRelationshipSourceStatusesWith(preds ...predicate.RelationshipSourceStatus) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newRelationshipSourceStatusesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntities applies the HasEdge predicate on the "entities" edge.
func HasEntities() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntitiesTable, EntitiesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntitiesWith applies the HasEdge predicate on the "entities" edge with a given conditions (other predicates).
func HasEntitiesWith(preds ...predicate.Entity) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newEntitiesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntityResourceRefs applies the HasEdge predicate on the "entity_resource_refs" edge.
func HasEntityResourceRefs() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntityResourceRefsTable, EntityResourceRefsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityResourceRefsWith applies the HasEdge predicate on the "entity_resource_refs" edge with a given conditions (other predicates).
func HasEntityResourceRefsWith(preds ...predicate.EntityResourceRef) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newEntityResourceRefsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntityIdentifiers applies the HasEdge predicate on the "entity_identifiers" edge.
func HasEntityIdentifiers() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntityIdentifiersTable, EntityIdentifiersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityIdentifiersWith applies the HasEdge predicate on the "entity_identifiers" edge with a given conditions (other predicates).
func HasEntityIdentifiersWith(preds ...predicate.EntityIdentifier) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newEntityIdentifiersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActionProposals applies the HasEdge predicate on the "action_proposals" edge.
func HasActionProposals() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActionProposalsTable, ActionProposalsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionProposalsWith applies the HasEdge predicate on the "action_proposals" edge with a given conditions (other predicates).
func HasActionProposalsWith(preds ...predicate.ActionProposal) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newActionProposalsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApprovalTokens applies the HasEdge predicate on the "approval_tokens" edge.
func HasApprovalTokens() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ApprovalTokensTable, ApprovalTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApprovalTokensWith applies the HasEdge predicate on the "approval_tokens" edge with a given conditions (other predicates).
func HasApprovalTokensWith(preds ...predicate.ApprovalToken) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newApprovalTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserPreferences applies the HasEdge predicate on the "user_preferences" edge.
func HasUserPreferences() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserPreferencesTable, UserPreferencesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserPreferencesWith applies the HasEdge predicate on the "user_preferences" edge with a given conditions (other predicates).
func HasUserPreferencesWith(preds ...predicate.UserPreference) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newUserPreferencesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConsoleResources applies the HasEdge predicate on the "console_resources" edge.
func HasConsoleResources() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ConsoleResourcesTable, ConsoleResourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConsoleResourcesWith applies the HasEdge predicate on the "console_resources" edge with a given conditions (other predicates).
func HasConsoleResourcesWith(preds ...predicate.ConsoleResource) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newConsoleResourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountDeletionChallenges applies the HasEdge predicate on the "account_deletion_challenges" edge.
func HasAccountDeletionChallenges() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountDeletionChallengesTable, AccountDeletionChallengesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountDeletionChallengesWith applies the HasEdge predicate on the "account_deletion_challenges" edge with a given conditions (other predicates).
func HasAccountDeletionChallengesWith(preds ...predicate.AccountDeletionChallenge) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAccountDeletionChallengesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTermsAssents applies the HasEdge predicate on the "terms_assents" edge.
func HasTermsAssents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TermsAssentsTable, TermsAssentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTermsAssentsWith applies the HasEdge predicate on the "terms_assents" edge with a given conditions (other predicates).
func HasTermsAssentsWith(preds ...predicate.TermsAssent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTermsAssentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
