// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/accountdeletionchallenge"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// AccountDeletionChallengeCreate is the builder for creating a AccountDeletionChallenge entity.
type AccountDeletionChallengeCreate struct {
	config
	mutation *AccountDeletionChallengeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountDeletionChallengeCreate) SetCreatedAt(v time.Time) *AccountDeletionChallengeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableCreatedAt(v *time.Time) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountDeletionChallengeCreate) SetUpdatedAt(v time.Time) *AccountDeletionChallengeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableUpdatedAt(v *time.Time) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *AccountDeletionChallengeCreate) SetMethod(v string) *AccountDeletionChallengeCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (_c *AccountDeletionChallengeCreate) SetBaselineAuthTime(v int64) *AccountDeletionChallengeCreate {
	_c.mutation.SetBaselineAuthTime(v)
	return _c
}

// SetNillableBaselineAuthTime sets the "baseline_auth_time" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableBaselineAuthTime(v *int64) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetBaselineAuthTime(*v)
	}
	return _c
}

// SetMfaRequired sets the "mfa_required" field.
func (_c *AccountDeletionChallengeCreate) SetMfaRequired(v bool) *AccountDeletionChallengeCreate {
	_c.mutation.SetMfaRequired(v)
	return _c
}

// SetNillableMfaRequired sets the "mfa_required" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableMfaRequired(v *bool) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetMfaRequired(*v)
	}
	return _c
}

// SetCodeHash sets the "code_hash" field.
func (_c *AccountDeletionChallengeCreate) SetCodeHash(v string) *AccountDeletionChallengeCreate {
	_c.mutation.SetCodeHash(v)
	return _c
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableCodeHash(v *string) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetCodeHash(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *AccountDeletionChallengeCreate) SetTokenHash(v string) *AccountDeletionChallengeCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableTokenHash(v *string) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetTokenHash(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *AccountDeletionChallengeCreate) SetAttempts(v int) *AccountDeletionChallengeCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableAttempts(v *int) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AccountDeletionChallengeCreate) SetExpiresAt(v time.Time) *AccountDeletionChallengeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *AccountDeletionChallengeCreate) SetVerifiedAt(v time.Time) *AccountDeletionChallengeCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableVerifiedAt(v *time.Time) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *AccountDeletionChallengeCreate) SetConsumedAt(v time.Time) *AccountDeletionChallengeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableConsumedAt(v *time.Time) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountDeletionChallengeCreate) SetID(v uuid.UUID) *AccountDeletionChallengeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountDeletionChallengeCreate) SetNillableID(v *uuid.UUID) *AccountDeletionChallengeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *AccountDeletionChallengeCreate) SetUserID(id uuid.UUID) *AccountDeletionChallengeCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *AccountDeletionChallengeCreate) SetUser(v *User) *AccountDeletionChallengeCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the AccountDeletionChallengeMutation object of the builder.
func (_c *AccountDeletionChallengeCreate) Mutation() *AccountDeletionChallengeMutation {
	return _c.mutation
}

// Save creates the AccountDeletionChallenge in the database.
func (_c *AccountDeletionChallengeCreate) Save(ctx context.Context) (*AccountDeletionChallenge, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountDeletionChallengeCreate) SaveX(ctx context.Context) *AccountDeletionChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDeletionChallengeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDeletionChallengeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountDeletionChallengeCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if accountdeletionchallenge.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountdeletionchallenge.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := accountdeletionchallenge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if accountdeletionchallenge.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountdeletionchallenge.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountdeletionchallenge.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.BaselineAuthTime(); !ok {
		v := accountdeletionchallenge.DefaultBaselineAuthTime
		_c.mutation.SetBaselineAuthTime(v)
	}
	if _, ok := _c.mutation.MfaRequired(); !ok {
		v := accountdeletionchallenge.DefaultMfaRequired
		_c.mutation.SetMfaRequired(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := accountdeletionchallenge.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if accountdeletionchallenge.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized accountdeletionchallenge.DefaultID (forgotten import ent/runtime?)")
		}
		v := accountdeletionchallenge.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountDeletionChallengeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountDeletionChallenge.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountDeletionChallenge.updated_at"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "AccountDeletionChallenge.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := accountdeletionchallenge.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaselineAuthTime(); !ok {
		return &ValidationError{Name: "baseline_auth_time", err: errors.New(`ent: missing required field "AccountDeletionChallenge.baseline_auth_time"`)}
	}
	if v, ok := _c.mutation.BaselineAuthTime(); ok {
		if err := accountdeletionchallenge.BaselineAuthTimeValidator(v); err != nil {
			return &ValidationError{Name: "baseline_auth_time", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.baseline_auth_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MfaRequired(); !ok {
		return &ValidationError{Name: "mfa_required", err: errors.New(`ent: missing required field "AccountDeletionChallenge.mfa_required"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "AccountDeletionChallenge.attempts"`)}
	}
	if v, ok := _c.mutation.Attempts(); ok {
		if err := accountdeletionchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.attempts": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AccountDeletionChallenge.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "AccountDeletionChallenge.user"`)}
	}
	return nil
}

func (_c *AccountDeletionChallengeCreate) sqlSave(ctx context.Context) (*AccountDeletionChallenge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountDeletionChallengeCreate) createSpec() (*AccountDeletionChallenge, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountDeletionChallenge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountdeletionchallenge.Table, sqlgraph.NewFieldSpec(accountdeletionchallenge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(accountdeletionchallenge.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.BaselineAuthTime(); ok {
		_spec.SetField(accountdeletionchallenge.FieldBaselineAuthTime, field.TypeInt64, value)
		_node.BaselineAuthTime = value
	}
	if value, ok := _c.mutation.MfaRequired(); ok {
		_spec.SetField(accountdeletionchallenge.FieldMfaRequired, field.TypeBool, value)
		_node.MfaRequired = value
	}
	if value, ok := _c.mutation.CodeHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldCodeHash, field.TypeString, value)
		_node.CodeHash = &value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = &value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(accountdeletionchallenge.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountdeletionchallenge.UserTable,
			Columns: []string{accountdeletionchallenge.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_account_deletion_challenges = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountDeletionChallenge.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountDeletionChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountDeletionChallengeCreate) OnConflict(opts ...sql.ConflictOption) *AccountDeletionChallengeUpsertOne {
	_c.conflict = opts
	return &AccountDeletionChallengeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountDeletionChallengeCreate) OnConflictColumns(columns ...string) *AccountDeletionChallengeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountDeletionChallengeUpsertOne{
		create: _c,
	}
}

type (
	// AccountDeletionChallengeUpsertOne is the builder for "upsert"-ing
	//  one AccountDeletionChallenge node.
	AccountDeletionChallengeUpsertOne struct {
		create *AccountDeletionChallengeCreate
	}

	// AccountDeletionChallengeUpsert is the "OnConflict" setter.
	AccountDeletionChallengeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDeletionChallengeUpsert) SetUpdatedAt(v time.Time) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateUpdatedAt() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldUpdatedAt)
	return u
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsert) SetBaselineAuthTime(v int64) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldBaselineAuthTime, v)
	return u
}

// UpdateBaselineAuthTime sets the "baseline_auth_time" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateBaselineAuthTime() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldBaselineAuthTime)
	return u
}

// AddBaselineAuthTime adds v to the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsert) AddBaselineAuthTime(v int64) *AccountDeletionChallengeUpsert {
	u.Add(accountdeletionchallenge.FieldBaselineAuthTime, v)
	return u
}

// SetMfaRequired sets the "mfa_required" field.
func (u *AccountDeletionChallengeUpsert) SetMfaRequired(v bool) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldMfaRequired, v)
	return u
}

// UpdateMfaRequired sets the "mfa_required" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateMfaRequired() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldMfaRequired)
	return u
}

// SetCodeHash sets the "code_hash" field.
func (u *AccountDeletionChallengeUpsert) SetCodeHash(v string) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldCodeHash, v)
	return u
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateCodeHash() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldCodeHash)
	return u
}

// ClearCodeHash clears the value of the "code_hash" field.
func (u *AccountDeletionChallengeUpsert) ClearCodeHash() *AccountDeletionChallengeUpsert {
	u.SetNull(accountdeletionchallenge.FieldCodeHash)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *AccountDeletionChallengeUpsert) SetTokenHash(v string) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateTokenHash() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldTokenHash)
	return u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *AccountDeletionChallengeUpsert) ClearTokenHash() *AccountDeletionChallengeUpsert {
	u.SetNull(accountdeletionchallenge.FieldTokenHash)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *AccountDeletionChallengeUpsert) SetAttempts(v int) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateAttempts() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *AccountDeletionChallengeUpsert) AddAttempts(v int) *AccountDeletionChallengeUpsert {
	u.Add(accountdeletionchallenge.FieldAttempts, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountDeletionChallengeUpsert) SetExpiresAt(v time.Time) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateExpiresAt() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldExpiresAt)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AccountDeletionChallengeUpsert) SetVerifiedAt(v time.Time) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateVerifiedAt() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *AccountDeletionChallengeUpsert) ClearVerifiedAt() *AccountDeletionChallengeUpsert {
	u.SetNull(accountdeletionchallenge.FieldVerifiedAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AccountDeletionChallengeUpsert) SetConsumedAt(v time.Time) *AccountDeletionChallengeUpsert {
	u.Set(accountdeletionchallenge.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsert) UpdateConsumedAt() *AccountDeletionChallengeUpsert {
	u.SetExcluded(accountdeletionchallenge.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AccountDeletionChallengeUpsert) ClearConsumedAt() *AccountDeletionChallengeUpsert {
	u.SetNull(accountdeletionchallenge.FieldConsumedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountdeletionchallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountDeletionChallengeUpsertOne) UpdateNewValues() *AccountDeletionChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(accountdeletionchallenge.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountdeletionchallenge.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Method(); exists {
			s.SetIgnore(accountdeletionchallenge.FieldMethod)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountDeletionChallengeUpsertOne) Ignore() *AccountDeletionChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountDeletionChallengeUpsertOne) DoNothing() *AccountDeletionChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountDeletionChallengeCreate.OnConflict
// documentation for more info.
func (u *AccountDeletionChallengeUpsertOne) Update(set func(*AccountDeletionChallengeUpsert)) *AccountDeletionChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountDeletionChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDeletionChallengeUpsertOne) SetUpdatedAt(v time.Time) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateUpdatedAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsertOne) SetBaselineAuthTime(v int64) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetBaselineAuthTime(v)
	})
}

// AddBaselineAuthTime adds v to the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsertOne) AddBaselineAuthTime(v int64) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.AddBaselineAuthTime(v)
	})
}

// UpdateBaselineAuthTime sets the "baseline_auth_time" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateBaselineAuthTime() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateBaselineAuthTime()
	})
}

// SetMfaRequired sets the "mfa_required" field.
func (u *AccountDeletionChallengeUpsertOne) SetMfaRequired(v bool) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetMfaRequired(v)
	})
}

// UpdateMfaRequired sets the "mfa_required" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateMfaRequired() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateMfaRequired()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *AccountDeletionChallengeUpsertOne) SetCodeHash(v string) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateCodeHash() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateCodeHash()
	})
}

// ClearCodeHash clears the value of the "code_hash" field.
func (u *AccountDeletionChallengeUpsertOne) ClearCodeHash() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearCodeHash()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *AccountDeletionChallengeUpsertOne) SetTokenHash(v string) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateTokenHash() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *AccountDeletionChallengeUpsertOne) ClearTokenHash() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearTokenHash()
	})
}

// SetAttempts sets the "attempts" field.
func (u *AccountDeletionChallengeUpsertOne) SetAttempts(v int) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *AccountDeletionChallengeUpsertOne) AddAttempts(v int) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateAttempts() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateAttempts()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountDeletionChallengeUpsertOne) SetExpiresAt(v time.Time) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateExpiresAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AccountDeletionChallengeUpsertOne) SetVerifiedAt(v time.Time) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateVerifiedAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *AccountDeletionChallengeUpsertOne) ClearVerifiedAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AccountDeletionChallengeUpsertOne) SetConsumedAt(v time.Time) *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertOne) UpdateConsumedAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AccountDeletionChallengeUpsertOne) ClearConsumedAt() *AccountDeletionChallengeUpsertOne {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AccountDeletionChallengeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountDeletionChallengeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountDeletionChallengeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountDeletionChallengeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AccountDeletionChallengeUpsertOne.ID is not supported by MySQL driver. Use AccountDeletionChallengeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountDeletionChallengeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountDeletionChallengeCreateBulk is the builder for creating many AccountDeletionChallenge entities in bulk.
type AccountDeletionChallengeCreateBulk struct {
	config
	err      error
	builders []*AccountDeletionChallengeCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountDeletionChallenge entities in the database.
func (_c *AccountDeletionChallengeCreateBulk) Save(ctx context.Context) ([]*AccountDeletionChallenge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountDeletionChallenge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountDeletionChallengeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountDeletionChallengeCreateBulk) SaveX(ctx context.Context) []*AccountDeletionChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDeletionChallengeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDeletionChallengeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountDeletionChallenge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountDeletionChallengeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountDeletionChallengeCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountDeletionChallengeUpsertBulk {
	_c.conflict = opts
	return &AccountDeletionChallengeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountDeletionChallengeCreateBulk) OnConflictColumns(columns ...string) *AccountDeletionChallengeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountDeletionChallengeUpsertBulk{
		create: _c,
	}
}

// AccountDeletionChallengeUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountDeletionChallenge nodes.
type AccountDeletionChallengeUpsertBulk struct {
	create *AccountDeletionChallengeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(accountdeletionchallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AccountDeletionChallengeUpsertBulk) UpdateNewValues() *AccountDeletionChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(accountdeletionchallenge.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountdeletionchallenge.FieldCreatedAt)
			}
			if _, exists := b.mutation.Method(); exists {
				s.SetIgnore(accountdeletionchallenge.FieldMethod)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountDeletionChallenge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountDeletionChallengeUpsertBulk) Ignore() *AccountDeletionChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountDeletionChallengeUpsertBulk) DoNothing() *AccountDeletionChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountDeletionChallengeCreateBulk.OnConflict
// documentation for more info.
func (u *AccountDeletionChallengeUpsertBulk) Update(set func(*AccountDeletionChallengeUpsert)) *AccountDeletionChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountDeletionChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountDeletionChallengeUpsertBulk) SetUpdatedAt(v time.Time) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateUpdatedAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsertBulk) SetBaselineAuthTime(v int64) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetBaselineAuthTime(v)
	})
}

// AddBaselineAuthTime adds v to the "baseline_auth_time" field.
func (u *AccountDeletionChallengeUpsertBulk) AddBaselineAuthTime(v int64) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.AddBaselineAuthTime(v)
	})
}

// UpdateBaselineAuthTime sets the "baseline_auth_time" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateBaselineAuthTime() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateBaselineAuthTime()
	})
}

// SetMfaRequired sets the "mfa_required" field.
func (u *AccountDeletionChallengeUpsertBulk) SetMfaRequired(v bool) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetMfaRequired(v)
	})
}

// UpdateMfaRequired sets the "mfa_required" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateMfaRequired() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateMfaRequired()
	})
}

// SetCodeHash sets the "code_hash" field.
func (u *AccountDeletionChallengeUpsertBulk) SetCodeHash(v string) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetCodeHash(v)
	})
}

// UpdateCodeHash sets the "code_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateCodeHash() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateCodeHash()
	})
}

// ClearCodeHash clears the value of the "code_hash" field.
func (u *AccountDeletionChallengeUpsertBulk) ClearCodeHash() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearCodeHash()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *AccountDeletionChallengeUpsertBulk) SetTokenHash(v string) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateTokenHash() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *AccountDeletionChallengeUpsertBulk) ClearTokenHash() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearTokenHash()
	})
}

// SetAttempts sets the "attempts" field.
func (u *AccountDeletionChallengeUpsertBulk) SetAttempts(v int) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *AccountDeletionChallengeUpsertBulk) AddAttempts(v int) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateAttempts() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateAttempts()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AccountDeletionChallengeUpsertBulk) SetExpiresAt(v time.Time) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateExpiresAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *AccountDeletionChallengeUpsertBulk) SetVerifiedAt(v time.Time) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateVerifiedAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *AccountDeletionChallengeUpsertBulk) ClearVerifiedAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *AccountDeletionChallengeUpsertBulk) SetConsumedAt(v time.Time) *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *AccountDeletionChallengeUpsertBulk) UpdateConsumedAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *AccountDeletionChallengeUpsertBulk) ClearConsumedAt() *AccountDeletionChallengeUpsertBulk {
	return u.Update(func(s *AccountDeletionChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// Exec executes the query.
func (u *AccountDeletionChallengeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountDeletionChallengeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountDeletionChallengeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountDeletionChallengeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
