// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/accountdeletionchallenge"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// AccountDeletionChallenge is the model entity for the AccountDeletionChallenge schema.
type AccountDeletionChallenge struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// BaselineAuthTime holds the value of the "baseline_auth_time" field.
	BaselineAuthTime int64 `json:"baseline_auth_time,omitempty"`
	// MfaRequired holds the value of the "mfa_required" field.
	MfaRequired bool `json:"mfa_required,omitempty"`
	// CodeHash holds the value of the "code_hash" field.
	CodeHash *string `json:"-"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash *string `json:"-"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountDeletionChallengeQuery when eager-loading is set.
	Edges                            AccountDeletionChallengeEdges `json:"edges"`
	user_account_deletion_challenges *uuid.UUID
	selectValues                     sql.SelectValues
}

// AccountDeletionChallengeEdges holds the relations/edges for other nodes in the graph.
type AccountDeletionChallengeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountDeletionChallengeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountDeletionChallenge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountdeletionchallenge.FieldMfaRequired:
			values[i] = new(sql.NullBool)
		case accountdeletionchallenge.FieldBaselineAuthTime, accountdeletionchallenge.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case accountdeletionchallenge.FieldMethod, accountdeletionchallenge.FieldCodeHash, accountdeletionchallenge.FieldTokenHash:
			values[i] = new(sql.NullString)
		case accountdeletionchallenge.FieldCreatedAt, accountdeletionchallenge.FieldUpdatedAt, accountdeletionchallenge.FieldExpiresAt, accountdeletionchallenge.FieldVerifiedAt, accountdeletionchallenge.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		case accountdeletionchallenge.FieldID:
			values[i] = new(uuid.UUID)
		case accountdeletionchallenge.ForeignKeys[0]: // user_account_deletion_challenges
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountDeletionChallenge fields.
func (_m *AccountDeletionChallenge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountdeletionchallenge.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case accountdeletionchallenge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountdeletionchallenge.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountdeletionchallenge.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case accountdeletionchallenge.FieldBaselineAuthTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field baseline_auth_time", values[i])
			} else if value.Valid {
				_m.BaselineAuthTime = value.Int64
			}
		case accountdeletionchallenge.FieldMfaRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mfa_required", values[i])
			} else if value.Valid {
				_m.MfaRequired = value.Bool
			}
		case accountdeletionchallenge.FieldCodeHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_hash", values[i])
			} else if value.Valid {
				_m.CodeHash = new(string)
				*_m.CodeHash = value.String
			}
		case accountdeletionchallenge.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = new(string)
				*_m.TokenHash = value.String
			}
		case accountdeletionchallenge.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case accountdeletionchallenge.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case accountdeletionchallenge.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		case accountdeletionchallenge.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case accountdeletionchallenge.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_account_deletion_challenges", values[i])
			} else if value.Valid {
				_m.user_account_deletion_challenges = new(uuid.UUID)
				*_m.user_account_deletion_challenges = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountDeletionChallenge.
// This includes values selected through modifiers, order, etc.
func (_m *AccountDeletionChallenge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the AccountDeletionChallenge entity.
func (_m *AccountDeletionChallenge) QueryUser() *UserQuery {
	return NewAccountDeletionChallengeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this AccountDeletionChallenge.
// Note that you need to call AccountDeletionChallenge.Unwrap() before calling this method if this AccountDeletionChallenge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountDeletionChallenge) Update() *AccountDeletionChallengeUpdateOne {
	return NewAccountDeletionChallengeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountDeletionChallenge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountDeletionChallenge) Unwrap() *AccountDeletionChallenge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountDeletionChallenge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountDeletionChallenge) String() string {
	var builder strings.Builder
	builder.WriteString("AccountDeletionChallenge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("baseline_auth_time=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaselineAuthTime))
	builder.WriteString(", ")
	builder.WriteString("mfa_required=")
	builder.WriteString(fmt.Sprintf("%v", _m.MfaRequired))
	builder.WriteString(", ")
	builder.WriteString("code_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AccountDeletionChallenges is a parsable slice of AccountDeletionChallenge.
type AccountDeletionChallenges []*AccountDeletionChallenge
