// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/accountdeletionchallenge"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
)

// AccountDeletionChallengeUpdate is the builder for updating AccountDeletionChallenge entities.
type AccountDeletionChallengeUpdate struct {
	config
	hooks    []Hook
	mutation *AccountDeletionChallengeMutation
}

// Where appends a list predicates to the AccountDeletionChallengeUpdate builder.
func (_u *AccountDeletionChallengeUpdate) Where(ps ...predicate.AccountDeletionChallenge) *AccountDeletionChallengeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountDeletionChallengeUpdate) SetUpdatedAt(v time.Time) *AccountDeletionChallengeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (_u *AccountDeletionChallengeUpdate) SetBaselineAuthTime(v int64) *AccountDeletionChallengeUpdate {
	_u.mutation.ResetBaselineAuthTime()
	_u.mutation.SetBaselineAuthTime(v)
	return _u
}

// SetNillableBaselineAuthTime sets the "baseline_auth_time" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableBaselineAuthTime(v *int64) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetBaselineAuthTime(*v)
	}
	return _u
}

// AddBaselineAuthTime adds value to the "baseline_auth_time" field.
func (_u *AccountDeletionChallengeUpdate) AddBaselineAuthTime(v int64) *AccountDeletionChallengeUpdate {
	_u.mutation.AddBaselineAuthTime(v)
	return _u
}

// SetMfaRequired sets the "mfa_required" field.
func (_u *AccountDeletionChallengeUpdate) SetMfaRequired(v bool) *AccountDeletionChallengeUpdate {
	_u.mutation.SetMfaRequired(v)
	return _u
}

// SetNillableMfaRequired sets the "mfa_required" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableMfaRequired(v *bool) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetMfaRequired(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *AccountDeletionChallengeUpdate) SetCodeHash(v string) *AccountDeletionChallengeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableCodeHash(v *string) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// ClearCodeHash clears the value of the "code_hash" field.
func (_u *AccountDeletionChallengeUpdate) ClearCodeHash() *AccountDeletionChallengeUpdate {
	_u.mutation.ClearCodeHash()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AccountDeletionChallengeUpdate) SetTokenHash(v string) *AccountDeletionChallengeUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableTokenHash(v *string) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *AccountDeletionChallengeUpdate) ClearTokenHash() *AccountDeletionChallengeUpdate {
	_u.mutation.ClearTokenHash()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AccountDeletionChallengeUpdate) SetAttempts(v int) *AccountDeletionChallengeUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableAttempts(v *int) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AccountDeletionChallengeUpdate) AddAttempts(v int) *AccountDeletionChallengeUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccountDeletionChallengeUpdate) SetExpiresAt(v time.Time) *AccountDeletionChallengeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableExpiresAt(v *time.Time) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *AccountDeletionChallengeUpdate) SetVerifiedAt(v time.Time) *AccountDeletionChallengeUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableVerifiedAt(v *time.Time) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *AccountDeletionChallengeUpdate) ClearVerifiedAt() *AccountDeletionChallengeUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AccountDeletionChallengeUpdate) SetConsumedAt(v time.Time) *AccountDeletionChallengeUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdate) SetNillableConsumedAt(v *time.Time) *AccountDeletionChallengeUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AccountDeletionChallengeUpdate) ClearConsumedAt() *AccountDeletionChallengeUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AccountDeletionChallengeMutation object of the builder.
func (_u *AccountDeletionChallengeUpdate) Mutation() *AccountDeletionChallengeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountDeletionChallengeUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountDeletionChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountDeletionChallengeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountDeletionChallengeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountDeletionChallengeUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if accountdeletionchallenge.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountdeletionchallenge.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountdeletionchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountDeletionChallengeUpdate) check() error {
	if v, ok := _u.mutation.BaselineAuthTime(); ok {
		if err := accountdeletionchallenge.BaselineAuthTimeValidator(v); err != nil {
			return &ValidationError{Name: "baseline_auth_time", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.baseline_auth_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := accountdeletionchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.attempts": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountDeletionChallenge.user"`)
	}
	return nil
}

func (_u *AccountDeletionChallengeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountdeletionchallenge.Table, accountdeletionchallenge.Columns, sqlgraph.NewFieldSpec(accountdeletionchallenge.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaselineAuthTime(); ok {
		_spec.SetField(accountdeletionchallenge.FieldBaselineAuthTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaselineAuthTime(); ok {
		_spec.AddField(accountdeletionchallenge.FieldBaselineAuthTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MfaRequired(); ok {
		_spec.SetField(accountdeletionchallenge.FieldMfaRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldCodeHash, field.TypeString, value)
	}
	if _u.mutation.CodeHashCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldCodeHash, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(accountdeletionchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(accountdeletionchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountdeletionchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountDeletionChallengeUpdateOne is the builder for updating a single AccountDeletionChallenge entity.
type AccountDeletionChallengeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountDeletionChallengeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountDeletionChallengeUpdateOne) SetUpdatedAt(v time.Time) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaselineAuthTime sets the "baseline_auth_time" field.
func (_u *AccountDeletionChallengeUpdateOne) SetBaselineAuthTime(v int64) *AccountDeletionChallengeUpdateOne {
	_u.mutation.ResetBaselineAuthTime()
	_u.mutation.SetBaselineAuthTime(v)
	return _u
}

// SetNillableBaselineAuthTime sets the "baseline_auth_time" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableBaselineAuthTime(v *int64) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetBaselineAuthTime(*v)
	}
	return _u
}

// AddBaselineAuthTime adds value to the "baseline_auth_time" field.
func (_u *AccountDeletionChallengeUpdateOne) AddBaselineAuthTime(v int64) *AccountDeletionChallengeUpdateOne {
	_u.mutation.AddBaselineAuthTime(v)
	return _u
}

// SetMfaRequired sets the "mfa_required" field.
func (_u *AccountDeletionChallengeUpdateOne) SetMfaRequired(v bool) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetMfaRequired(v)
	return _u
}

// SetNillableMfaRequired sets the "mfa_required" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableMfaRequired(v *bool) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetMfaRequired(*v)
	}
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *AccountDeletionChallengeUpdateOne) SetCodeHash(v string) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableCodeHash(v *string) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// ClearCodeHash clears the value of the "code_hash" field.
func (_u *AccountDeletionChallengeUpdateOne) ClearCodeHash() *AccountDeletionChallengeUpdateOne {
	_u.mutation.ClearCodeHash()
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *AccountDeletionChallengeUpdateOne) SetTokenHash(v string) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableTokenHash(v *string) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *AccountDeletionChallengeUpdateOne) ClearTokenHash() *AccountDeletionChallengeUpdateOne {
	_u.mutation.ClearTokenHash()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *AccountDeletionChallengeUpdateOne) SetAttempts(v int) *AccountDeletionChallengeUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableAttempts(v *int) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *AccountDeletionChallengeUpdateOne) AddAttempts(v int) *AccountDeletionChallengeUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AccountDeletionChallengeUpdateOne) SetExpiresAt(v time.Time) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableExpiresAt(v *time.Time) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *AccountDeletionChallengeUpdateOne) SetVerifiedAt(v time.Time) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableVerifiedAt(v *time.Time) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *AccountDeletionChallengeUpdateOne) ClearVerifiedAt() *AccountDeletionChallengeUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *AccountDeletionChallengeUpdateOne) SetConsumedAt(v time.Time) *AccountDeletionChallengeUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *AccountDeletionChallengeUpdateOne) SetNillableConsumedAt(v *time.Time) *AccountDeletionChallengeUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *AccountDeletionChallengeUpdateOne) ClearConsumedAt() *AccountDeletionChallengeUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the AccountDeletionChallengeMutation object of the builder.
func (_u *AccountDeletionChallengeUpdateOne) Mutation() *AccountDeletionChallengeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountDeletionChallengeUpdate builder.
func (_u *AccountDeletionChallengeUpdateOne) Where(ps ...predicate.AccountDeletionChallenge) *AccountDeletionChallengeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountDeletionChallengeUpdateOne) Select(field string, fields ...string) *AccountDeletionChallengeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountDeletionChallenge entity.
func (_u *AccountDeletionChallengeUpdateOne) Save(ctx context.Context) (*AccountDeletionChallenge, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountDeletionChallengeUpdateOne) SaveX(ctx context.Context) *AccountDeletionChallenge {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountDeletionChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountDeletionChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountDeletionChallengeUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if accountdeletionchallenge.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized accountdeletionchallenge.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := accountdeletionchallenge.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountDeletionChallengeUpdateOne) check() error {
	if v, ok := _u.mutation.BaselineAuthTime(); ok {
		if err := accountdeletionchallenge.BaselineAuthTimeValidator(v); err != nil {
			return &ValidationError{Name: "baseline_auth_time", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.baseline_auth_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempts(); ok {
		if err := accountdeletionchallenge.AttemptsValidator(v); err != nil {
			return &ValidationError{Name: "attempts", err: fmt.Errorf(`ent: validator failed for field "AccountDeletionChallenge.attempts": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountDeletionChallenge.user"`)
	}
	return nil
}

func (_u *AccountDeletionChallengeUpdateOne) sqlSave(ctx context.Context) (_node *AccountDeletionChallenge, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountdeletionchallenge.Table, accountdeletionchallenge.Columns, sqlgraph.NewFieldSpec(accountdeletionchallenge.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountDeletionChallenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountdeletionchallenge.FieldID)
		for _, f := range fields {
			if !accountdeletionchallenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountdeletionchallenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaselineAuthTime(); ok {
		_spec.SetField(accountdeletionchallenge.FieldBaselineAuthTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaselineAuthTime(); ok {
		_spec.AddField(accountdeletionchallenge.FieldBaselineAuthTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MfaRequired(); ok {
		_spec.SetField(accountdeletionchallenge.FieldMfaRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldCodeHash, field.TypeString, value)
	}
	if _u.mutation.CodeHashCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldCodeHash, field.TypeString)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(accountdeletionchallenge.FieldTokenHash, field.TypeString, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(accountdeletionchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(accountdeletionchallenge.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(accountdeletionchallenge.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(accountdeletionchallenge.FieldConsumedAt, field.TypeTime)
	}
	_node = &AccountDeletionChallenge{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountdeletionchallenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
