// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/billingretention"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
)

// BillingRetentionUpdate is the builder for updating BillingRetention entities.
type BillingRetentionUpdate struct {
	config
	hooks    []Hook
	mutation *BillingRetentionMutation
}

// Where appends a list predicates to the BillingRetentionUpdate builder.
func (_u *BillingRetentionUpdate) Where(ps ...predicate.BillingRetention) *BillingRetentionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingRetentionUpdate) SetUpdatedAt(v time.Time) *BillingRetentionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BillingRetentionMutation object of the builder.
func (_u *BillingRetentionUpdate) Mutation() *BillingRetentionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillingRetentionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingRetentionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillingRetentionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingRetentionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingRetentionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingretention.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BillingRetentionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(billingretention.Table, billingretention.Columns, sqlgraph.NewFieldSpec(billingretention.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingretention.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(billingretention.FieldStripeCustomerID, field.TypeString)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(billingretention.FieldStripeSubscriptionID, field.TypeString)
	}
	if _u.mutation.TrialExpiresAtCleared() {
		_spec.ClearField(billingretention.FieldTrialExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingretention.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillingRetentionUpdateOne is the builder for updating a single BillingRetention entity.
type BillingRetentionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillingRetentionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BillingRetentionUpdateOne) SetUpdatedAt(v time.Time) *BillingRetentionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BillingRetentionMutation object of the builder.
func (_u *BillingRetentionUpdateOne) Mutation() *BillingRetentionMutation {
	return _u.mutation
}

// Where appends a list predicates to the BillingRetentionUpdate builder.
func (_u *BillingRetentionUpdateOne) Where(ps ...predicate.BillingRetention) *BillingRetentionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillingRetentionUpdateOne) Select(field string, fields ...string) *BillingRetentionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillingRetention entity.
func (_u *BillingRetentionUpdateOne) Save(ctx context.Context) (*BillingRetention, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillingRetentionUpdateOne) SaveX(ctx context.Context) *BillingRetention {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillingRetentionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillingRetentionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BillingRetentionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := billingretention.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BillingRetentionUpdateOne) sqlSave(ctx context.Context) (_node *BillingRetention, err error) {
	_spec := sqlgraph.NewUpdateSpec(billingretention.Table, billingretention.Columns, sqlgraph.NewFieldSpec(billingretention.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillingRetention.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billingretention.FieldID)
		for _, f := range fields {
			if !billingretention.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billingretention.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(billingretention.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(billingretention.FieldStripeCustomerID, field.TypeString)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(billingretention.FieldStripeSubscriptionID, field.TypeString)
	}
	if _u.mutation.TrialExpiresAtCleared() {
		_spec.ClearField(billingretention.FieldTrialExpiresAt, field.TypeTime)
	}
	_node = &BillingRetention{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billingretention.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
