// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/billingretention"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
)

// BillingRetentionDelete is the builder for deleting a BillingRetention entity.
type BillingRetentionDelete struct {
	config
	hooks    []Hook
	mutation *BillingRetentionMutation
}

// Where appends a list predicates to the BillingRetentionDelete builder.
func (_d *BillingRetentionDelete) Where(ps ...predicate.BillingRetention) *BillingRetentionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BillingRetentionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BillingRetentionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BillingRetentionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(billingretention.Table, sqlgraph.NewFieldSpec(billingretention.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BillingRetentionDeleteOne is the builder for deleting a single BillingRetention entity.
type BillingRetentionDeleteOne struct {
	_d *BillingRetentionDelete
}

// Where appends a list predicates to the BillingRetentionDelete builder.
func (_d *BillingRetentionDeleteOne) Where(ps ...predicate.BillingRetention) *BillingRetentionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BillingRetentionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{billingretention.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BillingRetentionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
