// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/billingretention"
	"github.com/google/uuid"
)

// BillingRetention is the model entity for the BillingRetention schema.
type BillingRetention struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Plan holds the value of the "plan" field.
	Plan string `json:"plan,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StripeCustomerID holds the value of the "stripe_customer_id" field.
	StripeCustomerID string `json:"stripe_customer_id,omitempty"`
	// StripeSubscriptionID holds the value of the "stripe_subscription_id" field.
	StripeSubscriptionID string `json:"stripe_subscription_id,omitempty"`
	// TrialExpiresAt holds the value of the "trial_expires_at" field.
	TrialExpiresAt *time.Time `json:"trial_expires_at,omitempty"`
	// RetainedAt holds the value of the "retained_at" field.
	RetainedAt   time.Time `json:"retained_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingRetention) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billingretention.FieldPlan, billingretention.FieldStatus, billingretention.FieldStripeCustomerID, billingretention.FieldStripeSubscriptionID:
			values[i] = new(sql.NullString)
		case billingretention.FieldCreatedAt, billingretention.FieldUpdatedAt, billingretention.FieldTrialExpiresAt, billingretention.FieldRetainedAt:
			values[i] = new(sql.NullTime)
		case billingretention.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingRetention fields.
func (_m *BillingRetention) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billingretention.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case billingretention.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billingretention.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billingretention.FieldPlan:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan", values[i])
			} else if value.Valid {
				_m.Plan = value.String
			}
		case billingretention.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case billingretention.FieldStripeCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_customer_id", values[i])
			} else if value.Valid {
				_m.StripeCustomerID = value.String
			}
		case billingretention.FieldStripeSubscriptionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_subscription_id", values[i])
			} else if value.Valid {
				_m.StripeSubscriptionID = value.String
			}
		case billingretention.FieldTrialExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field trial_expires_at", values[i])
			} else if value.Valid {
				_m.TrialExpiresAt = new(time.Time)
				*_m.TrialExpiresAt = value.Time
			}
		case billingretention.FieldRetainedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retained_at", values[i])
			} else if value.Valid {
				_m.RetainedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingRetention.
// This includes values selected through modifiers, order, etc.
func (_m *BillingRetention) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BillingRetention.
// Note that you need to call BillingRetention.Unwrap() before calling this method if this BillingRetention
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingRetention) Update() *BillingRetentionUpdateOne {
	return NewBillingRetentionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingRetention entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingRetention) Unwrap() *BillingRetention {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingRetention is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingRetention) String() string {
	var builder strings.Builder
	builder.WriteString("BillingRetention(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("plan=")
	builder.WriteString(_m.Plan)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("stripe_customer_id=")
	builder.WriteString(_m.StripeCustomerID)
	builder.WriteString(", ")
	builder.WriteString("stripe_subscription_id=")
	builder.WriteString(_m.StripeSubscriptionID)
	builder.WriteString(", ")
	if v := _m.TrialExpiresAt; v != nil {
		builder.WriteString("trial_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("retained_at=")
	builder.WriteString(_m.RetainedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BillingRetentions is a parsable slice of BillingRetention.
type BillingRetentions []*BillingRetention
