// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/termsassent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// TermsAssent is the model entity for the TermsAssent schema.
type TermsAssent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TermsVersion holds the value of the "terms_version" field.
	TermsVersion string `json:"terms_version,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt time.Time `json:"accepted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TermsAssentQuery when eager-loading is set.
	Edges              TermsAssentEdges `json:"edges"`
	user_terms_assents *uuid.UUID
	selectValues       sql.SelectValues
}

// TermsAssentEdges holds the relations/edges for other nodes in the graph.
type TermsAssentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TermsAssentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TermsAssent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case termsassent.FieldTermsVersion:
			values[i] = new(sql.NullString)
		case termsassent.FieldCreatedAt, termsassent.FieldUpdatedAt, termsassent.FieldAcceptedAt:
			values[i] = new(sql.NullTime)
		case termsassent.FieldID:
			values[i] = new(uuid.UUID)
		case termsassent.ForeignKeys[0]: // user_terms_assents
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TermsAssent fields.
func (_m *TermsAssent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case termsassent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case termsassent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case termsassent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case termsassent.FieldTermsVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field terms_version", values[i])
			} else if value.Valid {
				_m.TermsVersion = value.String
			}
		case termsassent.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = value.Time
			}
		case termsassent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_terms_assents", values[i])
			} else if value.Valid {
				_m.user_terms_assents = new(uuid.UUID)
				*_m.user_terms_assents = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TermsAssent.
// This includes values selected through modifiers, order, etc.
func (_m *TermsAssent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the TermsAssent entity.
func (_m *TermsAssent) QueryUser() *UserQuery {
	return NewTermsAssentClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TermsAssent.
// Note that you need to call TermsAssent.Unwrap() before calling this method if this TermsAssent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TermsAssent) Update() *TermsAssentUpdateOne {
	return NewTermsAssentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TermsAssent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TermsAssent) Unwrap() *TermsAssent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TermsAssent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TermsAssent) String() string {
	var builder strings.Builder
	builder.WriteString("TermsAssent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("terms_version=")
	builder.WriteString(_m.TermsVersion)
	builder.WriteString(", ")
	builder.WriteString("accepted_at=")
	builder.WriteString(_m.AcceptedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TermsAssents is a parsable slice of TermsAssent.
type TermsAssents []*TermsAssent
