// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/predicate"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/termsassent"
)

// TermsAssentUpdate is the builder for updating TermsAssent entities.
type TermsAssentUpdate struct {
	config
	hooks    []Hook
	mutation *TermsAssentMutation
}

// Where appends a list predicates to the TermsAssentUpdate builder.
func (_u *TermsAssentUpdate) Where(ps ...predicate.TermsAssent) *TermsAssentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TermsAssentUpdate) SetUpdatedAt(v time.Time) *TermsAssentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TermsAssentMutation object of the builder.
func (_u *TermsAssentUpdate) Mutation() *TermsAssentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TermsAssentUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TermsAssentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TermsAssentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TermsAssentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TermsAssentUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if termsassent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized termsassent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := termsassent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TermsAssentUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TermsAssent.user"`)
	}
	return nil
}

func (_u *TermsAssentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(termsassent.Table, termsassent.Columns, sqlgraph.NewFieldSpec(termsassent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(termsassent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{termsassent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TermsAssentUpdateOne is the builder for updating a single TermsAssent entity.
type TermsAssentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TermsAssentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TermsAssentUpdateOne) SetUpdatedAt(v time.Time) *TermsAssentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TermsAssentMutation object of the builder.
func (_u *TermsAssentUpdateOne) Mutation() *TermsAssentMutation {
	return _u.mutation
}

// Where appends a list predicates to the TermsAssentUpdate builder.
func (_u *TermsAssentUpdateOne) Where(ps ...predicate.TermsAssent) *TermsAssentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TermsAssentUpdateOne) Select(field string, fields ...string) *TermsAssentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TermsAssent entity.
func (_u *TermsAssentUpdateOne) Save(ctx context.Context) (*TermsAssent, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TermsAssentUpdateOne) SaveX(ctx context.Context) *TermsAssent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TermsAssentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TermsAssentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TermsAssentUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if termsassent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized termsassent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := termsassent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TermsAssentUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TermsAssent.user"`)
	}
	return nil
}

func (_u *TermsAssentUpdateOne) sqlSave(ctx context.Context) (_node *TermsAssent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(termsassent.Table, termsassent.Columns, sqlgraph.NewFieldSpec(termsassent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TermsAssent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, termsassent.FieldID)
		for _, f := range fields {
			if !termsassent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != termsassent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(termsassent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TermsAssent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{termsassent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
