// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/termsassent"
	"github.com/Oppulence-Engineering/rowboat/apps/rowboat-api/ent/user"
	"github.com/google/uuid"
)

// TermsAssentCreate is the builder for creating a TermsAssent entity.
type TermsAssentCreate struct {
	config
	mutation *TermsAssentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TermsAssentCreate) SetCreatedAt(v time.Time) *TermsAssentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TermsAssentCreate) SetNillableCreatedAt(v *time.Time) *TermsAssentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TermsAssentCreate) SetUpdatedAt(v time.Time) *TermsAssentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TermsAssentCreate) SetNillableUpdatedAt(v *time.Time) *TermsAssentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTermsVersion sets the "terms_version" field.
func (_c *TermsAssentCreate) SetTermsVersion(v string) *TermsAssentCreate {
	_c.mutation.SetTermsVersion(v)
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *TermsAssentCreate) SetAcceptedAt(v time.Time) *TermsAssentCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *TermsAssentCreate) SetID(v uuid.UUID) *TermsAssentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TermsAssentCreate) SetNillableID(v *uuid.UUID) *TermsAssentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TermsAssentCreate) SetUserID(id uuid.UUID) *TermsAssentCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TermsAssentCreate) SetUser(v *User) *TermsAssentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TermsAssentMutation object of the builder.
func (_c *TermsAssentCreate) Mutation() *TermsAssentMutation {
	return _c.mutation
}

// Save creates the TermsAssent in the database.
func (_c *TermsAssentCreate) Save(ctx context.Context) (*TermsAssent, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TermsAssentCreate) SaveX(ctx context.Context) *TermsAssent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermsAssentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermsAssentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TermsAssentCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if termsassent.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized termsassent.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := termsassent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if termsassent.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized termsassent.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := termsassent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if termsassent.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized termsassent.DefaultID (forgotten import ent/runtime?)")
		}
		v := termsassent.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TermsAssentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TermsAssent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TermsAssent.updated_at"`)}
	}
	if _, ok := _c.mutation.TermsVersion(); !ok {
		return &ValidationError{Name: "terms_version", err: errors.New(`ent: missing required field "TermsAssent.terms_version"`)}
	}
	if v, ok := _c.mutation.TermsVersion(); ok {
		if err := termsassent.TermsVersionValidator(v); err != nil {
			return &ValidationError{Name: "terms_version", err: fmt.Errorf(`ent: validator failed for field "TermsAssent.terms_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AcceptedAt(); !ok {
		return &ValidationError{Name: "accepted_at", err: errors.New(`ent: missing required field "TermsAssent.accepted_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TermsAssent.user"`)}
	}
	return nil
}

func (_c *TermsAssentCreate) sqlSave(ctx context.Context) (*TermsAssent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TermsAssentCreate) createSpec() (*TermsAssent, *sqlgraph.CreateSpec) {
	var (
		_node = &TermsAssent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(termsassent.Table, sqlgraph.NewFieldSpec(termsassent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(termsassent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(termsassent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TermsVersion(); ok {
		_spec.SetField(termsassent.FieldTermsVersion, field.TypeString, value)
		_node.TermsVersion = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(termsassent.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   termsassent.UserTable,
			Columns: []string{termsassent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_terms_assents = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TermsAssent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TermsAssentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TermsAssentCreate) OnConflict(opts ...sql.ConflictOption) *TermsAssentUpsertOne {
	_c.conflict = opts
	return &TermsAssentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TermsAssentCreate) OnConflictColumns(columns ...string) *TermsAssentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TermsAssentUpsertOne{
		create: _c,
	}
}

type (
	// TermsAssentUpsertOne is the builder for "upsert"-ing
	//  one TermsAssent node.
	TermsAssentUpsertOne struct {
		create *TermsAssentCreate
	}

	// TermsAssentUpsert is the "OnConflict" setter.
	TermsAssentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TermsAssentUpsert) SetUpdatedAt(v time.Time) *TermsAssentUpsert {
	u.Set(termsassent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TermsAssentUpsert) UpdateUpdatedAt() *TermsAssentUpsert {
	u.SetExcluded(termsassent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(termsassent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TermsAssentUpsertOne) UpdateNewValues() *TermsAssentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(termsassent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(termsassent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TermsVersion(); exists {
			s.SetIgnore(termsassent.FieldTermsVersion)
		}
		if _, exists := u.create.mutation.AcceptedAt(); exists {
			s.SetIgnore(termsassent.FieldAcceptedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TermsAssentUpsertOne) Ignore() *TermsAssentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TermsAssentUpsertOne) DoNothing() *TermsAssentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TermsAssentCreate.OnConflict
// documentation for more info.
func (u *TermsAssentUpsertOne) Update(set func(*TermsAssentUpsert)) *TermsAssentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TermsAssentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TermsAssentUpsertOne) SetUpdatedAt(v time.Time) *TermsAssentUpsertOne {
	return u.Update(func(s *TermsAssentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TermsAssentUpsertOne) UpdateUpdatedAt() *TermsAssentUpsertOne {
	return u.Update(func(s *TermsAssentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TermsAssentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TermsAssentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TermsAssentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TermsAssentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TermsAssentUpsertOne.ID is not supported by MySQL driver. Use TermsAssentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TermsAssentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TermsAssentCreateBulk is the builder for creating many TermsAssent entities in bulk.
type TermsAssentCreateBulk struct {
	config
	err      error
	builders []*TermsAssentCreate
	conflict []sql.ConflictOption
}

// Save creates the TermsAssent entities in the database.
func (_c *TermsAssentCreateBulk) Save(ctx context.Context) ([]*TermsAssent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TermsAssent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TermsAssentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TermsAssentCreateBulk) SaveX(ctx context.Context) []*TermsAssent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TermsAssentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TermsAssentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TermsAssent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TermsAssentUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TermsAssentCreateBulk) OnConflict(opts ...sql.ConflictOption) *TermsAssentUpsertBulk {
	_c.conflict = opts
	return &TermsAssentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TermsAssentCreateBulk) OnConflictColumns(columns ...string) *TermsAssentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TermsAssentUpsertBulk{
		create: _c,
	}
}

// TermsAssentUpsertBulk is the builder for "upsert"-ing
// a bulk of TermsAssent nodes.
type TermsAssentUpsertBulk struct {
	create *TermsAssentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(termsassent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TermsAssentUpsertBulk) UpdateNewValues() *TermsAssentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(termsassent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(termsassent.FieldCreatedAt)
			}
			if _, exists := b.mutation.TermsVersion(); exists {
				s.SetIgnore(termsassent.FieldTermsVersion)
			}
			if _, exists := b.mutation.AcceptedAt(); exists {
				s.SetIgnore(termsassent.FieldAcceptedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TermsAssent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TermsAssentUpsertBulk) Ignore() *TermsAssentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TermsAssentUpsertBulk) DoNothing() *TermsAssentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TermsAssentCreateBulk.OnConflict
// documentation for more info.
func (u *TermsAssentUpsertBulk) Update(set func(*TermsAssentUpsert)) *TermsAssentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TermsAssentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TermsAssentUpsertBulk) SetUpdatedAt(v time.Time) *TermsAssentUpsertBulk {
	return u.Update(func(s *TermsAssentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TermsAssentUpsertBulk) UpdateUpdatedAt() *TermsAssentUpsertBulk {
	return u.Update(func(s *TermsAssentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TermsAssentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TermsAssentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TermsAssentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TermsAssentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
