// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// AccountDeletionChallenge is the client for interacting with the AccountDeletionChallenge builders.
	AccountDeletionChallenge *AccountDeletionChallengeClient
	// ActionOutcome is the client for interacting with the ActionOutcome builders.
	ActionOutcome *ActionOutcomeClient
	// ActionProposal is the client for interacting with the ActionProposal builders.
	ActionProposal *ActionProposalClient
	// AgentApproval is the client for interacting with the AgentApproval builders.
	AgentApproval *AgentApprovalClient
	// AgentDefinition is the client for interacting with the AgentDefinition builders.
	AgentDefinition *AgentDefinitionClient
	// AgentDefinitionHistory is the client for interacting with the AgentDefinitionHistory builders.
	AgentDefinitionHistory *AgentDefinitionHistoryClient
	// AgentSession is the client for interacting with the AgentSession builders.
	AgentSession *AgentSessionClient
	// AgentSessionEvent is the client for interacting with the AgentSessionEvent builders.
	AgentSessionEvent *AgentSessionEventClient
	// AgentToolCall is the client for interacting with the AgentToolCall builders.
	AgentToolCall *AgentToolCallClient
	// AgentToolResultBlob is the client for interacting with the AgentToolResultBlob builders.
	AgentToolResultBlob *AgentToolResultBlobClient
	// AgentTurn is the client for interacting with the AgentTurn builders.
	AgentTurn *AgentTurnClient
	// ApprovalToken is the client for interacting with the ApprovalToken builders.
	ApprovalToken *ApprovalTokenClient
	// BackgroundTask is the client for interacting with the BackgroundTask builders.
	BackgroundTask *BackgroundTaskClient
	// BackgroundTaskArtifact is the client for interacting with the BackgroundTaskArtifact builders.
	BackgroundTaskArtifact *BackgroundTaskArtifactClient
	// BackgroundTaskRun is the client for interacting with the BackgroundTaskRun builders.
	BackgroundTaskRun *BackgroundTaskRunClient
	// BackgroundTaskRunEvent is the client for interacting with the BackgroundTaskRunEvent builders.
	BackgroundTaskRunEvent *BackgroundTaskRunEventClient
	// BackgroundTaskScheduleState is the client for interacting with the BackgroundTaskScheduleState builders.
	BackgroundTaskScheduleState *BackgroundTaskScheduleStateClient
	// CaptureArtifact is the client for interacting with the CaptureArtifact builders.
	CaptureArtifact *CaptureArtifactClient
	// CloudEvent is the client for interacting with the CloudEvent builders.
	CloudEvent *CloudEventClient
	// Commitment is the client for interacting with the Commitment builders.
	Commitment *CommitmentClient
	// CommitmentDependency is the client for interacting with the CommitmentDependency builders.
	CommitmentDependency *CommitmentDependencyClient
	// CommitmentEvent is the client for interacting with the CommitmentEvent builders.
	CommitmentEvent *CommitmentEventClient
	// CommunicationAttachment is the client for interacting with the CommunicationAttachment builders.
	CommunicationAttachment *CommunicationAttachmentClient
	// CommunicationInteraction is the client for interacting with the CommunicationInteraction builders.
	CommunicationInteraction *CommunicationInteractionClient
	// CommunicationParticipant is the client for interacting with the CommunicationParticipant builders.
	CommunicationParticipant *CommunicationParticipantClient
	// CommunicationPrivacyPolicy is the client for interacting with the CommunicationPrivacyPolicy builders.
	CommunicationPrivacyPolicy *CommunicationPrivacyPolicyClient
	// CommunicationPrivacyRule is the client for interacting with the CommunicationPrivacyRule builders.
	CommunicationPrivacyRule *CommunicationPrivacyRuleClient
	// CommunicationShareGrant is the client for interacting with the CommunicationShareGrant builders.
	CommunicationShareGrant *CommunicationShareGrantClient
	// CommunicationSyncCursor is the client for interacting with the CommunicationSyncCursor builders.
	CommunicationSyncCursor *CommunicationSyncCursorClient
	// ConnectorAuditEvent is the client for interacting with the ConnectorAuditEvent builders.
	ConnectorAuditEvent *ConnectorAuditEventClient
	// ConnectorCredentialCleanupJob is the client for interacting with the ConnectorCredentialCleanupJob builders.
	ConnectorCredentialCleanupJob *ConnectorCredentialCleanupJobClient
	// ConnectorCredentialRecovery is the client for interacting with the ConnectorCredentialRecovery builders.
	ConnectorCredentialRecovery *ConnectorCredentialRecoveryClient
	// ConnectorRevocationJob is the client for interacting with the ConnectorRevocationJob builders.
	ConnectorRevocationJob *ConnectorRevocationJobClient
	// ConsoleResource is the client for interacting with the ConsoleResource builders.
	ConsoleResource *ConsoleResourceClient
	// ConversationIntelligenceArtifact is the client for interacting with the ConversationIntelligenceArtifact builders.
	ConversationIntelligenceArtifact *ConversationIntelligenceArtifactClient
	// CreditLedger is the client for interacting with the CreditLedger builders.
	CreditLedger *CreditLedgerClient
	// DeletedIdentity is the client for interacting with the DeletedIdentity builders.
	DeletedIdentity *DeletedIdentityClient
	// Entity is the client for interacting with the Entity builders.
	Entity *EntityClient
	// EntityIdentifier is the client for interacting with the EntityIdentifier builders.
	EntityIdentifier *EntityIdentifierClient
	// EntityResourceRef is the client for interacting with the EntityResourceRef builders.
	EntityResourceRef *EntityResourceRefClient
	// GoogleWatch is the client for interacting with the GoogleWatch builders.
	GoogleWatch *GoogleWatchClient
	// LLMUsage is the client for interacting with the LLMUsage builders.
	LLMUsage *LLMUsageClient
	// LLMUsageHistory is the client for interacting with the LLMUsageHistory builders.
	LLMUsageHistory *LLMUsageHistoryClient
	// MCPConnection is the client for interacting with the MCPConnection builders.
	MCPConnection *MCPConnectionClient
	// MCPConnectionHistory is the client for interacting with the MCPConnectionHistory builders.
	MCPConnectionHistory *MCPConnectionHistoryClient
	// MailBodyCache is the client for interacting with the MailBodyCache builders.
	MailBodyCache *MailBodyCacheClient
	// MailMessageMeta is the client for interacting with the MailMessageMeta builders.
	MailMessageMeta *MailMessageMetaClient
	// MailSignal is the client for interacting with the MailSignal builders.
	MailSignal *MailSignalClient
	// MailThread is the client for interacting with the MailThread builders.
	MailThread *MailThreadClient
	// MeetingMinuteUsage is the client for interacting with the MeetingMinuteUsage builders.
	MeetingMinuteUsage *MeetingMinuteUsageClient
	// OAuthConnection is the client for interacting with the OAuthConnection builders.
	OAuthConnection *OAuthConnectionClient
	// OAuthConnectionHistory is the client for interacting with the OAuthConnectionHistory builders.
	OAuthConnectionHistory *OAuthConnectionHistoryClient
	// OAuthPending is the client for interacting with the OAuthPending builders.
	OAuthPending *OAuthPendingClient
	// Person is the client for interacting with the Person builders.
	Person *PersonClient
	// PersonAttribute is the client for interacting with the PersonAttribute builders.
	PersonAttribute *PersonAttributeClient
	// PersonIdentity is the client for interacting with the PersonIdentity builders.
	PersonIdentity *PersonIdentityClient
	// PersonInteractionStat is the client for interacting with the PersonInteractionStat builders.
	PersonInteractionStat *PersonInteractionStatClient
	// PersonMergeCandidate is the client for interacting with the PersonMergeCandidate builders.
	PersonMergeCandidate *PersonMergeCandidateClient
	// PersonSuppression is the client for interacting with the PersonSuppression builders.
	PersonSuppression *PersonSuppressionClient
	// PolicyDecisionSnapshot is the client for interacting with the PolicyDecisionSnapshot builders.
	PolicyDecisionSnapshot *PolicyDecisionSnapshotClient
	// Relationship is the client for interacting with the Relationship builders.
	Relationship *RelationshipClient
	// RelationshipAssertion is the client for interacting with the RelationshipAssertion builders.
	RelationshipAssertion *RelationshipAssertionClient
	// RelationshipAttentionItem is the client for interacting with the RelationshipAttentionItem builders.
	RelationshipAttentionItem *RelationshipAttentionItemClient
	// RelationshipIdentity is the client for interacting with the RelationshipIdentity builders.
	RelationshipIdentity *RelationshipIdentityClient
	// RelationshipIdentityCandidate is the client for interacting with the RelationshipIdentityCandidate builders.
	RelationshipIdentityCandidate *RelationshipIdentityCandidateClient
	// RelationshipIdentityDecision is the client for interacting with the RelationshipIdentityDecision builders.
	RelationshipIdentityDecision *RelationshipIdentityDecisionClient
	// RelationshipLineageEvent is the client for interacting with the RelationshipLineageEvent builders.
	RelationshipLineageEvent *RelationshipLineageEventClient
	// RelationshipObservation is the client for interacting with the RelationshipObservation builders.
	RelationshipObservation *RelationshipObservationClient
	// RelationshipParticipant is the client for interacting with the RelationshipParticipant builders.
	RelationshipParticipant *RelationshipParticipantClient
	// RelationshipProjectionJob is the client for interacting with the RelationshipProjectionJob builders.
	RelationshipProjectionJob *RelationshipProjectionJobClient
	// RelationshipReviewAcknowledgement is the client for interacting with the RelationshipReviewAcknowledgement builders.
	RelationshipReviewAcknowledgement *RelationshipReviewAcknowledgementClient
	// RelationshipSourceStatus is the client for interacting with the RelationshipSourceStatus builders.
	RelationshipSourceStatus *RelationshipSourceStatusClient
	// RelationshipStateSnapshot is the client for interacting with the RelationshipStateSnapshot builders.
	RelationshipStateSnapshot *RelationshipStateSnapshotClient
	// RevenueAction is the client for interacting with the RevenueAction builders.
	RevenueAction *RevenueActionClient
	// RevenueActionRevision is the client for interacting with the RevenueActionRevision builders.
	RevenueActionRevision *RevenueActionRevisionClient
	// RevenueEvidence is the client for interacting with the RevenueEvidence builders.
	RevenueEvidence *RevenueEvidenceClient
	// RevenueLeakScan is the client for interacting with the RevenueLeakScan builders.
	RevenueLeakScan *RevenueLeakScanClient
	// RevenueOutboxEvent is the client for interacting with the RevenueOutboxEvent builders.
	RevenueOutboxEvent *RevenueOutboxEventClient
	// RevenueTrustEvent is the client for interacting with the RevenueTrustEvent builders.
	RevenueTrustEvent *RevenueTrustEventClient
	// RevenueWorkspace is the client for interacting with the RevenueWorkspace builders.
	RevenueWorkspace *RevenueWorkspaceClient
	// RevenueWorkspaceMember is the client for interacting with the RevenueWorkspaceMember builders.
	RevenueWorkspaceMember *RevenueWorkspaceMemberClient
	// Subscription is the client for interacting with the Subscription builders.
	Subscription *SubscriptionClient
	// SubscriptionHistory is the client for interacting with the SubscriptionHistory builders.
	SubscriptionHistory *SubscriptionHistoryClient
	// TenantEvidenceKey is the client for interacting with the TenantEvidenceKey builders.
	TenantEvidenceKey *TenantEvidenceKeyClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserHistory is the client for interacting with the UserHistory builders.
	UserHistory *UserHistoryClient
	// UserPreference is the client for interacting with the UserPreference builders.
	UserPreference *UserPreferenceClient
	// VoiceAPIKey is the client for interacting with the VoiceAPIKey builders.
	VoiceAPIKey *VoiceAPIKeyClient
	// VoiceSyncItem is the client for interacting with the VoiceSyncItem builders.
	VoiceSyncItem *VoiceSyncItemClient
	// WorkspaceFeatureControl is the client for interacting with the WorkspaceFeatureControl builders.
	WorkspaceFeatureControl *WorkspaceFeatureControlClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.AccountDeletionChallenge = NewAccountDeletionChallengeClient(tx.config)
	tx.ActionOutcome = NewActionOutcomeClient(tx.config)
	tx.ActionProposal = NewActionProposalClient(tx.config)
	tx.AgentApproval = NewAgentApprovalClient(tx.config)
	tx.AgentDefinition = NewAgentDefinitionClient(tx.config)
	tx.AgentDefinitionHistory = NewAgentDefinitionHistoryClient(tx.config)
	tx.AgentSession = NewAgentSessionClient(tx.config)
	tx.AgentSessionEvent = NewAgentSessionEventClient(tx.config)
	tx.AgentToolCall = NewAgentToolCallClient(tx.config)
	tx.AgentToolResultBlob = NewAgentToolResultBlobClient(tx.config)
	tx.AgentTurn = NewAgentTurnClient(tx.config)
	tx.ApprovalToken = NewApprovalTokenClient(tx.config)
	tx.BackgroundTask = NewBackgroundTaskClient(tx.config)
	tx.BackgroundTaskArtifact = NewBackgroundTaskArtifactClient(tx.config)
	tx.BackgroundTaskRun = NewBackgroundTaskRunClient(tx.config)
	tx.BackgroundTaskRunEvent = NewBackgroundTaskRunEventClient(tx.config)
	tx.BackgroundTaskScheduleState = NewBackgroundTaskScheduleStateClient(tx.config)
	tx.CaptureArtifact = NewCaptureArtifactClient(tx.config)
	tx.CloudEvent = NewCloudEventClient(tx.config)
	tx.Commitment = NewCommitmentClient(tx.config)
	tx.CommitmentDependency = NewCommitmentDependencyClient(tx.config)
	tx.CommitmentEvent = NewCommitmentEventClient(tx.config)
	tx.CommunicationAttachment = NewCommunicationAttachmentClient(tx.config)
	tx.CommunicationInteraction = NewCommunicationInteractionClient(tx.config)
	tx.CommunicationParticipant = NewCommunicationParticipantClient(tx.config)
	tx.CommunicationPrivacyPolicy = NewCommunicationPrivacyPolicyClient(tx.config)
	tx.CommunicationPrivacyRule = NewCommunicationPrivacyRuleClient(tx.config)
	tx.CommunicationShareGrant = NewCommunicationShareGrantClient(tx.config)
	tx.CommunicationSyncCursor = NewCommunicationSyncCursorClient(tx.config)
	tx.ConnectorAuditEvent = NewConnectorAuditEventClient(tx.config)
	tx.ConnectorCredentialCleanupJob = NewConnectorCredentialCleanupJobClient(tx.config)
	tx.ConnectorCredentialRecovery = NewConnectorCredentialRecoveryClient(tx.config)
	tx.ConnectorRevocationJob = NewConnectorRevocationJobClient(tx.config)
	tx.ConsoleResource = NewConsoleResourceClient(tx.config)
	tx.ConversationIntelligenceArtifact = NewConversationIntelligenceArtifactClient(tx.config)
	tx.CreditLedger = NewCreditLedgerClient(tx.config)
	tx.DeletedIdentity = NewDeletedIdentityClient(tx.config)
	tx.Entity = NewEntityClient(tx.config)
	tx.EntityIdentifier = NewEntityIdentifierClient(tx.config)
	tx.EntityResourceRef = NewEntityResourceRefClient(tx.config)
	tx.GoogleWatch = NewGoogleWatchClient(tx.config)
	tx.LLMUsage = NewLLMUsageClient(tx.config)
	tx.LLMUsageHistory = NewLLMUsageHistoryClient(tx.config)
	tx.MCPConnection = NewMCPConnectionClient(tx.config)
	tx.MCPConnectionHistory = NewMCPConnectionHistoryClient(tx.config)
	tx.MailBodyCache = NewMailBodyCacheClient(tx.config)
	tx.MailMessageMeta = NewMailMessageMetaClient(tx.config)
	tx.MailSignal = NewMailSignalClient(tx.config)
	tx.MailThread = NewMailThreadClient(tx.config)
	tx.MeetingMinuteUsage = NewMeetingMinuteUsageClient(tx.config)
	tx.OAuthConnection = NewOAuthConnectionClient(tx.config)
	tx.OAuthConnectionHistory = NewOAuthConnectionHistoryClient(tx.config)
	tx.OAuthPending = NewOAuthPendingClient(tx.config)
	tx.Person = NewPersonClient(tx.config)
	tx.PersonAttribute = NewPersonAttributeClient(tx.config)
	tx.PersonIdentity = NewPersonIdentityClient(tx.config)
	tx.PersonInteractionStat = NewPersonInteractionStatClient(tx.config)
	tx.PersonMergeCandidate = NewPersonMergeCandidateClient(tx.config)
	tx.PersonSuppression = NewPersonSuppressionClient(tx.config)
	tx.PolicyDecisionSnapshot = NewPolicyDecisionSnapshotClient(tx.config)
	tx.Relationship = NewRelationshipClient(tx.config)
	tx.RelationshipAssertion = NewRelationshipAssertionClient(tx.config)
	tx.RelationshipAttentionItem = NewRelationshipAttentionItemClient(tx.config)
	tx.RelationshipIdentity = NewRelationshipIdentityClient(tx.config)
	tx.RelationshipIdentityCandidate = NewRelationshipIdentityCandidateClient(tx.config)
	tx.RelationshipIdentityDecision = NewRelationshipIdentityDecisionClient(tx.config)
	tx.RelationshipLineageEvent = NewRelationshipLineageEventClient(tx.config)
	tx.RelationshipObservation = NewRelationshipObservationClient(tx.config)
	tx.RelationshipParticipant = NewRelationshipParticipantClient(tx.config)
	tx.RelationshipProjectionJob = NewRelationshipProjectionJobClient(tx.config)
	tx.RelationshipReviewAcknowledgement = NewRelationshipReviewAcknowledgementClient(tx.config)
	tx.RelationshipSourceStatus = NewRelationshipSourceStatusClient(tx.config)
	tx.RelationshipStateSnapshot = NewRelationshipStateSnapshotClient(tx.config)
	tx.RevenueAction = NewRevenueActionClient(tx.config)
	tx.RevenueActionRevision = NewRevenueActionRevisionClient(tx.config)
	tx.RevenueEvidence = NewRevenueEvidenceClient(tx.config)
	tx.RevenueLeakScan = NewRevenueLeakScanClient(tx.config)
	tx.RevenueOutboxEvent = NewRevenueOutboxEventClient(tx.config)
	tx.RevenueTrustEvent = NewRevenueTrustEventClient(tx.config)
	tx.RevenueWorkspace = NewRevenueWorkspaceClient(tx.config)
	tx.RevenueWorkspaceMember = NewRevenueWorkspaceMemberClient(tx.config)
	tx.Subscription = NewSubscriptionClient(tx.config)
	tx.SubscriptionHistory = NewSubscriptionHistoryClient(tx.config)
	tx.TenantEvidenceKey = NewTenantEvidenceKeyClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.UserHistory = NewUserHistoryClient(tx.config)
	tx.UserPreference = NewUserPreferenceClient(tx.config)
	tx.VoiceAPIKey = NewVoiceAPIKeyClient(tx.config)
	tx.VoiceSyncItem = NewVoiceSyncItemClient(tx.config)
	tx.WorkspaceFeatureControl = NewWorkspaceFeatureControlClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: AccountDeletionChallenge.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
